package generator

import (
	"google.golang.org/protobuf/compiler/protogen"
)

const (
	jxPkg   = protogen.GoImportPath("github.com/go-faster/jx")
	jxpbPkg = protogen.GoImportPath("github.com/gopherex/protoc-gen-go-jx/jxpb")
)

// GenerateFile emits <prefix>.pb.jx.go next to the .pb.go for one proto file.
func GenerateFile(plugin *protogen.Plugin, file *protogen.File) error {
	msgs := flattenMessages(file.Messages)
	if len(msgs) == 0 {
		return nil
	}
	g := plugin.NewGeneratedFile(file.GeneratedFilenamePrefix+".pb.jx.go", file.GoImportPath)
	g.P("// Code generated by protoc-gen-go-jx. DO NOT EDIT.")
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	for _, m := range msgs {
		genEncode(g, m)
		genDecode(g, m)
		genJSONWrappers(g, m)
	}
	return nil
}

// flattenMessages returns all non-map-entry messages, including nested ones.
func flattenMessages(msgs []*protogen.Message) []*protogen.Message {
	var out []*protogen.Message
	for _, m := range msgs {
		if m.Desc.IsMapEntry() {
			continue
		}
		out = append(out, m)
		out = append(out, flattenMessages(m.Messages)...)
	}
	return out
}

func genJSONWrappers(g *protogen.GeneratedFile, m *protogen.Message) {
	jxEnc := g.QualifiedGoIdent(jxPkg.Ident("Encoder"))
	jxDecBytes := g.QualifiedGoIdent(jxPkg.Ident("DecodeBytes"))
	g.P("func (m *", m.GoIdent, ") MarshalJSON() ([]byte, error) {")
	g.P("var e ", jxEnc)
	g.P("m.Encode(&e)")
	g.P("return e.Bytes(), nil")
	g.P("}")
	g.P()
	g.P("func (m *", m.GoIdent, ") UnmarshalJSON(data []byte) error {")
	g.P("d := ", jxDecBytes, "(data)")
	g.P("return m.Decode(d)")
	g.P("}")
	g.P()
}
