// Code generated by protoc-gen-go-jx. DO NOT EDIT.

package golden

import (
	fmt "fmt"
	jx "github.com/go-faster/jx"
	jxpb "github.com/gopherex/protoc-gen-go-jx/jxpb"
	strconv "strconv"
)

func (m *ScalarTypes) Encode(e *jx.Encoder) {
	if m == nil {
		e.ObjStart()
		e.ObjEnd()
		return
	}
	e.ObjStart()
	if m.FieldDouble != 0 {
		e.FieldStart("fieldDouble")
		jxpb.EncFloat64(e, m.FieldDouble)
	}
	if m.FieldFloat != 0 {
		e.FieldStart("fieldFloat")
		jxpb.EncFloat32(e, m.FieldFloat)
	}
	if m.FieldInt32 != 0 {
		e.FieldStart("fieldInt32")
		e.Int32(m.FieldInt32)
	}
	if m.FieldInt64 != 0 {
		e.FieldStart("fieldInt64")
		jxpb.EncInt64(e, m.FieldInt64)
	}
	if m.FieldUint32 != 0 {
		e.FieldStart("fieldUint32")
		e.UInt32(m.FieldUint32)
	}
	if m.FieldUint64 != 0 {
		e.FieldStart("fieldUint64")
		jxpb.EncUint64(e, m.FieldUint64)
	}
	if m.FieldSint32 != 0 {
		e.FieldStart("fieldSint32")
		e.Int32(m.FieldSint32)
	}
	if m.FieldSint64 != 0 {
		e.FieldStart("fieldSint64")
		jxpb.EncInt64(e, m.FieldSint64)
	}
	if m.FieldFixed32 != 0 {
		e.FieldStart("fieldFixed32")
		e.UInt32(m.FieldFixed32)
	}
	if m.FieldFixed64 != 0 {
		e.FieldStart("fieldFixed64")
		jxpb.EncUint64(e, m.FieldFixed64)
	}
	if m.FieldSfixed32 != 0 {
		e.FieldStart("fieldSfixed32")
		e.Int32(m.FieldSfixed32)
	}
	if m.FieldSfixed64 != 0 {
		e.FieldStart("fieldSfixed64")
		jxpb.EncInt64(e, m.FieldSfixed64)
	}
	if m.FieldBool != false {
		e.FieldStart("fieldBool")
		e.Bool(m.FieldBool)
	}
	if m.FieldString != "" {
		e.FieldStart("fieldString")
		e.Str(m.FieldString)
	}
	if len(m.FieldBytes) > 0 {
		e.FieldStart("fieldBytes")
		jxpb.EncBytes(e, m.FieldBytes)
	}
	e.ObjEnd()
}

func (m *ScalarTypes) Decode(d *jx.Decoder) error {
	return d.Obj(func(d *jx.Decoder, key string) error {
		switch key {
		case "fieldDouble":
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := jxpb.DecFloat64(d)
			if err != nil {
				return err
			}
			m.FieldDouble = v
			return nil
		case "fieldFloat":
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := jxpb.DecFloat32(d)
			if err != nil {
				return err
			}
			m.FieldFloat = v
			return nil
		case "fieldInt32":
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := jxpb.DecInt32(d)
			if err != nil {
				return err
			}
			m.FieldInt32 = v
			return nil
		case "fieldInt64":
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := jxpb.DecInt64(d)
			if err != nil {
				return err
			}
			m.FieldInt64 = v
			return nil
		case "fieldUint32":
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := jxpb.DecUint32(d)
			if err != nil {
				return err
			}
			m.FieldUint32 = v
			return nil
		case "fieldUint64":
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := jxpb.DecUint64(d)
			if err != nil {
				return err
			}
			m.FieldUint64 = v
			return nil
		case "fieldSint32":
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := jxpb.DecInt32(d)
			if err != nil {
				return err
			}
			m.FieldSint32 = v
			return nil
		case "fieldSint64":
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := jxpb.DecInt64(d)
			if err != nil {
				return err
			}
			m.FieldSint64 = v
			return nil
		case "fieldFixed32":
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := jxpb.DecUint32(d)
			if err != nil {
				return err
			}
			m.FieldFixed32 = v
			return nil
		case "fieldFixed64":
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := jxpb.DecUint64(d)
			if err != nil {
				return err
			}
			m.FieldFixed64 = v
			return nil
		case "fieldSfixed32":
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := jxpb.DecInt32(d)
			if err != nil {
				return err
			}
			m.FieldSfixed32 = v
			return nil
		case "fieldSfixed64":
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := jxpb.DecInt64(d)
			if err != nil {
				return err
			}
			m.FieldSfixed64 = v
			return nil
		case "fieldBool":
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := d.Bool()
			if err != nil {
				return err
			}
			m.FieldBool = v
			return nil
		case "fieldString":
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := d.Str()
			if err != nil {
				return err
			}
			m.FieldString = v
			return nil
		case "fieldBytes":
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := jxpb.DecBytes(d)
			if err != nil {
				return err
			}
			m.FieldBytes = v
			return nil
		default:
			return fmt.Errorf("unknown field %q", key)
		}
	})
}

func (m *ScalarTypes) MarshalJSON() ([]byte, error) {
	var e jx.Encoder
	m.Encode(&e)
	return e.Bytes(), nil
}

func (m *ScalarTypes) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return m.Decode(d)
}

func (m *OptionalScalarTypes) Encode(e *jx.Encoder) {
	if m == nil {
		e.ObjStart()
		e.ObjEnd()
		return
	}
	e.ObjStart()
	if m.FieldDouble != nil {
		e.FieldStart("fieldDouble")
		jxpb.EncFloat64(e, *m.FieldDouble)
	}
	if m.FieldFloat != nil {
		e.FieldStart("fieldFloat")
		jxpb.EncFloat32(e, *m.FieldFloat)
	}
	if m.FieldInt32 != nil {
		e.FieldStart("fieldInt32")
		e.Int32(*m.FieldInt32)
	}
	if m.FieldInt64 != nil {
		e.FieldStart("fieldInt64")
		jxpb.EncInt64(e, *m.FieldInt64)
	}
	if m.FieldUint32 != nil {
		e.FieldStart("fieldUint32")
		e.UInt32(*m.FieldUint32)
	}
	if m.FieldUint64 != nil {
		e.FieldStart("fieldUint64")
		jxpb.EncUint64(e, *m.FieldUint64)
	}
	if m.FieldSint32 != nil {
		e.FieldStart("fieldSint32")
		e.Int32(*m.FieldSint32)
	}
	if m.FieldSint64 != nil {
		e.FieldStart("fieldSint64")
		jxpb.EncInt64(e, *m.FieldSint64)
	}
	if m.FieldFixed32 != nil {
		e.FieldStart("fieldFixed32")
		e.UInt32(*m.FieldFixed32)
	}
	if m.FieldFixed64 != nil {
		e.FieldStart("fieldFixed64")
		jxpb.EncUint64(e, *m.FieldFixed64)
	}
	if m.FieldSfixed32 != nil {
		e.FieldStart("fieldSfixed32")
		e.Int32(*m.FieldSfixed32)
	}
	if m.FieldSfixed64 != nil {
		e.FieldStart("fieldSfixed64")
		jxpb.EncInt64(e, *m.FieldSfixed64)
	}
	if m.FieldBool != nil {
		e.FieldStart("fieldBool")
		e.Bool(*m.FieldBool)
	}
	if m.FieldString != nil {
		e.FieldStart("fieldString")
		e.Str(*m.FieldString)
	}
	if len(m.FieldBytes) > 0 {
		e.FieldStart("fieldBytes")
		jxpb.EncBytes(e, m.FieldBytes)
	}
	e.ObjEnd()
}

func (m *OptionalScalarTypes) Decode(d *jx.Decoder) error {
	return d.Obj(func(d *jx.Decoder, key string) error {
		switch key {
		case "fieldDouble":
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := jxpb.DecFloat64(d)
			if err != nil {
				return err
			}
			m.FieldDouble = &v
			return nil
		case "fieldFloat":
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := jxpb.DecFloat32(d)
			if err != nil {
				return err
			}
			m.FieldFloat = &v
			return nil
		case "fieldInt32":
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := jxpb.DecInt32(d)
			if err != nil {
				return err
			}
			m.FieldInt32 = &v
			return nil
		case "fieldInt64":
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := jxpb.DecInt64(d)
			if err != nil {
				return err
			}
			m.FieldInt64 = &v
			return nil
		case "fieldUint32":
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := jxpb.DecUint32(d)
			if err != nil {
				return err
			}
			m.FieldUint32 = &v
			return nil
		case "fieldUint64":
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := jxpb.DecUint64(d)
			if err != nil {
				return err
			}
			m.FieldUint64 = &v
			return nil
		case "fieldSint32":
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := jxpb.DecInt32(d)
			if err != nil {
				return err
			}
			m.FieldSint32 = &v
			return nil
		case "fieldSint64":
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := jxpb.DecInt64(d)
			if err != nil {
				return err
			}
			m.FieldSint64 = &v
			return nil
		case "fieldFixed32":
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := jxpb.DecUint32(d)
			if err != nil {
				return err
			}
			m.FieldFixed32 = &v
			return nil
		case "fieldFixed64":
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := jxpb.DecUint64(d)
			if err != nil {
				return err
			}
			m.FieldFixed64 = &v
			return nil
		case "fieldSfixed32":
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := jxpb.DecInt32(d)
			if err != nil {
				return err
			}
			m.FieldSfixed32 = &v
			return nil
		case "fieldSfixed64":
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := jxpb.DecInt64(d)
			if err != nil {
				return err
			}
			m.FieldSfixed64 = &v
			return nil
		case "fieldBool":
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := d.Bool()
			if err != nil {
				return err
			}
			m.FieldBool = &v
			return nil
		case "fieldString":
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := d.Str()
			if err != nil {
				return err
			}
			m.FieldString = &v
			return nil
		case "fieldBytes":
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := jxpb.DecBytes(d)
			if err != nil {
				return err
			}
			m.FieldBytes = v
			return nil
		default:
			return fmt.Errorf("unknown field %q", key)
		}
	})
}

func (m *OptionalScalarTypes) MarshalJSON() ([]byte, error) {
	var e jx.Encoder
	m.Encode(&e)
	return e.Bytes(), nil
}

func (m *OptionalScalarTypes) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return m.Decode(d)
}

func (m *RepeatedScalarTypes) Encode(e *jx.Encoder) {
	if m == nil {
		e.ObjStart()
		e.ObjEnd()
		return
	}
	e.ObjStart()
	if len(m.FieldDouble) > 0 {
		e.FieldStart("fieldDouble")
		e.ArrStart()
		for _, v := range m.FieldDouble {
			jxpb.EncFloat64(e, v)
		}
		e.ArrEnd()
	}
	if len(m.FieldFloat) > 0 {
		e.FieldStart("fieldFloat")
		e.ArrStart()
		for _, v := range m.FieldFloat {
			jxpb.EncFloat32(e, v)
		}
		e.ArrEnd()
	}
	if len(m.FieldInt32) > 0 {
		e.FieldStart("fieldInt32")
		e.ArrStart()
		for _, v := range m.FieldInt32 {
			e.Int32(v)
		}
		e.ArrEnd()
	}
	if len(m.FieldInt64) > 0 {
		e.FieldStart("fieldInt64")
		e.ArrStart()
		for _, v := range m.FieldInt64 {
			jxpb.EncInt64(e, v)
		}
		e.ArrEnd()
	}
	if len(m.FieldUint32) > 0 {
		e.FieldStart("fieldUint32")
		e.ArrStart()
		for _, v := range m.FieldUint32 {
			e.UInt32(v)
		}
		e.ArrEnd()
	}
	if len(m.FieldUint64) > 0 {
		e.FieldStart("fieldUint64")
		e.ArrStart()
		for _, v := range m.FieldUint64 {
			jxpb.EncUint64(e, v)
		}
		e.ArrEnd()
	}
	if len(m.FieldSint32) > 0 {
		e.FieldStart("fieldSint32")
		e.ArrStart()
		for _, v := range m.FieldSint32 {
			e.Int32(v)
		}
		e.ArrEnd()
	}
	if len(m.FieldSint64) > 0 {
		e.FieldStart("fieldSint64")
		e.ArrStart()
		for _, v := range m.FieldSint64 {
			jxpb.EncInt64(e, v)
		}
		e.ArrEnd()
	}
	if len(m.FieldFixed32) > 0 {
		e.FieldStart("fieldFixed32")
		e.ArrStart()
		for _, v := range m.FieldFixed32 {
			e.UInt32(v)
		}
		e.ArrEnd()
	}
	if len(m.FieldFixed64) > 0 {
		e.FieldStart("fieldFixed64")
		e.ArrStart()
		for _, v := range m.FieldFixed64 {
			jxpb.EncUint64(e, v)
		}
		e.ArrEnd()
	}
	if len(m.FieldSfixed32) > 0 {
		e.FieldStart("fieldSfixed32")
		e.ArrStart()
		for _, v := range m.FieldSfixed32 {
			e.Int32(v)
		}
		e.ArrEnd()
	}
	if len(m.FieldSfixed64) > 0 {
		e.FieldStart("fieldSfixed64")
		e.ArrStart()
		for _, v := range m.FieldSfixed64 {
			jxpb.EncInt64(e, v)
		}
		e.ArrEnd()
	}
	if len(m.FieldBool) > 0 {
		e.FieldStart("fieldBool")
		e.ArrStart()
		for _, v := range m.FieldBool {
			e.Bool(v)
		}
		e.ArrEnd()
	}
	if len(m.FieldString) > 0 {
		e.FieldStart("fieldString")
		e.ArrStart()
		for _, v := range m.FieldString {
			e.Str(v)
		}
		e.ArrEnd()
	}
	if len(m.FieldBytes) > 0 {
		e.FieldStart("fieldBytes")
		e.ArrStart()
		for _, v := range m.FieldBytes {
			jxpb.EncBytes(e, v)
		}
		e.ArrEnd()
	}
	e.ObjEnd()
}

func (m *RepeatedScalarTypes) Decode(d *jx.Decoder) error {
	return d.Obj(func(d *jx.Decoder, key string) error {
		switch key {
		case "fieldDouble":
			if d.Next() == jx.Null {
				return d.Null()
			}
			return d.Arr(func(d *jx.Decoder) error {
				v, err := jxpb.DecFloat64(d)
				if err != nil {
					return err
				}
				m.FieldDouble = append(m.FieldDouble, v)
				return nil
			})
		case "fieldFloat":
			if d.Next() == jx.Null {
				return d.Null()
			}
			return d.Arr(func(d *jx.Decoder) error {
				v, err := jxpb.DecFloat32(d)
				if err != nil {
					return err
				}
				m.FieldFloat = append(m.FieldFloat, v)
				return nil
			})
		case "fieldInt32":
			if d.Next() == jx.Null {
				return d.Null()
			}
			return d.Arr(func(d *jx.Decoder) error {
				v, err := jxpb.DecInt32(d)
				if err != nil {
					return err
				}
				m.FieldInt32 = append(m.FieldInt32, v)
				return nil
			})
		case "fieldInt64":
			if d.Next() == jx.Null {
				return d.Null()
			}
			return d.Arr(func(d *jx.Decoder) error {
				v, err := jxpb.DecInt64(d)
				if err != nil {
					return err
				}
				m.FieldInt64 = append(m.FieldInt64, v)
				return nil
			})
		case "fieldUint32":
			if d.Next() == jx.Null {
				return d.Null()
			}
			return d.Arr(func(d *jx.Decoder) error {
				v, err := jxpb.DecUint32(d)
				if err != nil {
					return err
				}
				m.FieldUint32 = append(m.FieldUint32, v)
				return nil
			})
		case "fieldUint64":
			if d.Next() == jx.Null {
				return d.Null()
			}
			return d.Arr(func(d *jx.Decoder) error {
				v, err := jxpb.DecUint64(d)
				if err != nil {
					return err
				}
				m.FieldUint64 = append(m.FieldUint64, v)
				return nil
			})
		case "fieldSint32":
			if d.Next() == jx.Null {
				return d.Null()
			}
			return d.Arr(func(d *jx.Decoder) error {
				v, err := jxpb.DecInt32(d)
				if err != nil {
					return err
				}
				m.FieldSint32 = append(m.FieldSint32, v)
				return nil
			})
		case "fieldSint64":
			if d.Next() == jx.Null {
				return d.Null()
			}
			return d.Arr(func(d *jx.Decoder) error {
				v, err := jxpb.DecInt64(d)
				if err != nil {
					return err
				}
				m.FieldSint64 = append(m.FieldSint64, v)
				return nil
			})
		case "fieldFixed32":
			if d.Next() == jx.Null {
				return d.Null()
			}
			return d.Arr(func(d *jx.Decoder) error {
				v, err := jxpb.DecUint32(d)
				if err != nil {
					return err
				}
				m.FieldFixed32 = append(m.FieldFixed32, v)
				return nil
			})
		case "fieldFixed64":
			if d.Next() == jx.Null {
				return d.Null()
			}
			return d.Arr(func(d *jx.Decoder) error {
				v, err := jxpb.DecUint64(d)
				if err != nil {
					return err
				}
				m.FieldFixed64 = append(m.FieldFixed64, v)
				return nil
			})
		case "fieldSfixed32":
			if d.Next() == jx.Null {
				return d.Null()
			}
			return d.Arr(func(d *jx.Decoder) error {
				v, err := jxpb.DecInt32(d)
				if err != nil {
					return err
				}
				m.FieldSfixed32 = append(m.FieldSfixed32, v)
				return nil
			})
		case "fieldSfixed64":
			if d.Next() == jx.Null {
				return d.Null()
			}
			return d.Arr(func(d *jx.Decoder) error {
				v, err := jxpb.DecInt64(d)
				if err != nil {
					return err
				}
				m.FieldSfixed64 = append(m.FieldSfixed64, v)
				return nil
			})
		case "fieldBool":
			if d.Next() == jx.Null {
				return d.Null()
			}
			return d.Arr(func(d *jx.Decoder) error {
				v, err := d.Bool()
				if err != nil {
					return err
				}
				m.FieldBool = append(m.FieldBool, v)
				return nil
			})
		case "fieldString":
			if d.Next() == jx.Null {
				return d.Null()
			}
			return d.Arr(func(d *jx.Decoder) error {
				v, err := d.Str()
				if err != nil {
					return err
				}
				m.FieldString = append(m.FieldString, v)
				return nil
			})
		case "fieldBytes":
			if d.Next() == jx.Null {
				return d.Null()
			}
			return d.Arr(func(d *jx.Decoder) error {
				v, err := jxpb.DecBytes(d)
				if err != nil {
					return err
				}
				m.FieldBytes = append(m.FieldBytes, v)
				return nil
			})
		default:
			return fmt.Errorf("unknown field %q", key)
		}
	})
}

func (m *RepeatedScalarTypes) MarshalJSON() ([]byte, error) {
	var e jx.Encoder
	m.Encode(&e)
	return e.Bytes(), nil
}

func (m *RepeatedScalarTypes) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return m.Decode(d)
}

func (m *Outer) Encode(e *jx.Encoder) {
	if m == nil {
		e.ObjStart()
		e.ObjEnd()
		return
	}
	e.ObjStart()
	if m.Inner != nil {
		e.FieldStart("inner")
		m.Inner.Encode(e)
	}
	if m.EnumField != 0 {
		e.FieldStart("enumField")
		if s, ok := Outer_NestedEnum_name[int32(m.EnumField)]; ok {
			e.Str(s)
		} else {
			e.Int32(int32(m.EnumField))
		}
	}
	if m.DeepInner != nil {
		e.FieldStart("deepInner")
		m.DeepInner.Encode(e)
	}
	e.ObjEnd()
}

func (m *Outer) Decode(d *jx.Decoder) error {
	return d.Obj(func(d *jx.Decoder, key string) error {
		switch key {
		case "inner":
			if d.Next() == jx.Null {
				return d.Null()
			}
			m.Inner = &Outer_Inner{}
			return m.Inner.Decode(d)
		case "enumField":
			switch d.Next() {
			case jx.String:
				s, err := d.Str()
				if err != nil {
					return err
				}
				n, ok := Outer_NestedEnum_value[s]
				if !ok {
					return fmt.Errorf("unknown enum value %q", s)
				}
				m.EnumField = Outer_NestedEnum(n)
				return nil
			case jx.Number:
				n, err := d.Int32()
				if err != nil {
					return err
				}
				m.EnumField = Outer_NestedEnum(n)
				return nil
			case jx.Null:
				return d.Null()
			default:
				return fmt.Errorf("invalid enum token %s", d.Next())
			}
		case "deepInner":
			if d.Next() == jx.Null {
				return d.Null()
			}
			m.DeepInner = &Outer_Inner_DeepInner{}
			return m.DeepInner.Decode(d)
		default:
			return fmt.Errorf("unknown field %q", key)
		}
	})
}

func (m *Outer) MarshalJSON() ([]byte, error) {
	var e jx.Encoder
	m.Encode(&e)
	return e.Bytes(), nil
}

func (m *Outer) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return m.Decode(d)
}

func (m *Outer_Inner) Encode(e *jx.Encoder) {
	if m == nil {
		e.ObjStart()
		e.ObjEnd()
		return
	}
	e.ObjStart()
	if m.NestedEnum != 0 {
		e.FieldStart("nestedEnum")
		if s, ok := Outer_NestedEnum_name[int32(m.NestedEnum)]; ok {
			e.Str(s)
		} else {
			e.Int32(int32(m.NestedEnum))
		}
	}
	if m.Deep != nil {
		e.FieldStart("deep")
		m.Deep.Encode(e)
	}
	e.ObjEnd()
}

func (m *Outer_Inner) Decode(d *jx.Decoder) error {
	return d.Obj(func(d *jx.Decoder, key string) error {
		switch key {
		case "nestedEnum":
			switch d.Next() {
			case jx.String:
				s, err := d.Str()
				if err != nil {
					return err
				}
				n, ok := Outer_NestedEnum_value[s]
				if !ok {
					return fmt.Errorf("unknown enum value %q", s)
				}
				m.NestedEnum = Outer_NestedEnum(n)
				return nil
			case jx.Number:
				n, err := d.Int32()
				if err != nil {
					return err
				}
				m.NestedEnum = Outer_NestedEnum(n)
				return nil
			case jx.Null:
				return d.Null()
			default:
				return fmt.Errorf("invalid enum token %s", d.Next())
			}
		case "deep":
			if d.Next() == jx.Null {
				return d.Null()
			}
			m.Deep = &Outer_Inner_DeepInner{}
			return m.Deep.Decode(d)
		default:
			return fmt.Errorf("unknown field %q", key)
		}
	})
}

func (m *Outer_Inner) MarshalJSON() ([]byte, error) {
	var e jx.Encoder
	m.Encode(&e)
	return e.Bytes(), nil
}

func (m *Outer_Inner) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return m.Decode(d)
}

func (m *Outer_Inner_DeepInner) Encode(e *jx.Encoder) {
	if m == nil {
		e.ObjStart()
		e.ObjEnd()
		return
	}
	e.ObjStart()
	if m.Value != "" {
		e.FieldStart("value")
		e.Str(m.Value)
	}
	e.ObjEnd()
}

func (m *Outer_Inner_DeepInner) Decode(d *jx.Decoder) error {
	return d.Obj(func(d *jx.Decoder, key string) error {
		switch key {
		case "value":
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := d.Str()
			if err != nil {
				return err
			}
			m.Value = v
			return nil
		default:
			return fmt.Errorf("unknown field %q", key)
		}
	})
}

func (m *Outer_Inner_DeepInner) MarshalJSON() ([]byte, error) {
	var e jx.Encoder
	m.Encode(&e)
	return e.Bytes(), nil
}

func (m *Outer_Inner_DeepInner) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return m.Decode(d)
}

func (m *EnumAndMessageFields) Encode(e *jx.Encoder) {
	if m == nil {
		e.ObjStart()
		e.ObjEnd()
		return
	}
	e.ObjStart()
	if m.SingularEnum != 0 {
		e.FieldStart("singularEnum")
		if s, ok := TopLevelEnum_name[int32(m.SingularEnum)]; ok {
			e.Str(s)
		} else {
			e.Int32(int32(m.SingularEnum))
		}
	}
	if m.OptionalEnum != nil {
		e.FieldStart("optionalEnum")
		if s, ok := TopLevelEnum_name[int32(*m.OptionalEnum)]; ok {
			e.Str(s)
		} else {
			e.Int32(int32(*m.OptionalEnum))
		}
	}
	if len(m.RepeatedEnum) > 0 {
		e.FieldStart("repeatedEnum")
		e.ArrStart()
		for _, v := range m.RepeatedEnum {
			if s, ok := TopLevelEnum_name[int32(v)]; ok {
				e.Str(s)
			} else {
				e.Int32(int32(v))
			}
		}
		e.ArrEnd()
	}
	if m.SingularMessage != nil {
		e.FieldStart("singularMessage")
		m.SingularMessage.Encode(e)
	}
	if m.OptionalMessage != nil {
		e.FieldStart("optionalMessage")
		m.OptionalMessage.Encode(e)
	}
	if len(m.RepeatedMessage) > 0 {
		e.FieldStart("repeatedMessage")
		e.ArrStart()
		for _, v := range m.RepeatedMessage {
			v.Encode(e)
		}
		e.ArrEnd()
	}
	if m.NestedEnum != 0 {
		e.FieldStart("nestedEnum")
		if s, ok := Outer_NestedEnum_name[int32(m.NestedEnum)]; ok {
			e.Str(s)
		} else {
			e.Int32(int32(m.NestedEnum))
		}
	}
	if m.NestedMessage != nil {
		e.FieldStart("nestedMessage")
		m.NestedMessage.Encode(e)
	}
	e.ObjEnd()
}

func (m *EnumAndMessageFields) Decode(d *jx.Decoder) error {
	return d.Obj(func(d *jx.Decoder, key string) error {
		switch key {
		case "singularEnum":
			switch d.Next() {
			case jx.String:
				s, err := d.Str()
				if err != nil {
					return err
				}
				n, ok := TopLevelEnum_value[s]
				if !ok {
					return fmt.Errorf("unknown enum value %q", s)
				}
				m.SingularEnum = TopLevelEnum(n)
				return nil
			case jx.Number:
				n, err := d.Int32()
				if err != nil {
					return err
				}
				m.SingularEnum = TopLevelEnum(n)
				return nil
			case jx.Null:
				return d.Null()
			default:
				return fmt.Errorf("invalid enum token %s", d.Next())
			}
		case "optionalEnum":
			switch d.Next() {
			case jx.String:
				s, err := d.Str()
				if err != nil {
					return err
				}
				n, ok := TopLevelEnum_value[s]
				if !ok {
					return fmt.Errorf("unknown enum value %q", s)
				}
				v := TopLevelEnum(n)
				m.OptionalEnum = &v
				return nil
			case jx.Number:
				n, err := d.Int32()
				if err != nil {
					return err
				}
				v := TopLevelEnum(n)
				m.OptionalEnum = &v
				return nil
			case jx.Null:
				return d.Null()
			default:
				return fmt.Errorf("invalid enum token %s", d.Next())
			}
		case "repeatedEnum":
			if d.Next() == jx.Null {
				return d.Null()
			}
			return d.Arr(func(d *jx.Decoder) error {
				var n int32
				switch d.Next() {
				case jx.String:
					s, err := d.Str()
					if err != nil {
						return err
					}
					v, ok := TopLevelEnum_value[s]
					if !ok {
						return fmt.Errorf("unknown enum value %q", s)
					}
					n = v
				default:
					v, err := d.Int32()
					if err != nil {
						return err
					}
					n = v
				}
				m.RepeatedEnum = append(m.RepeatedEnum, TopLevelEnum(n))
				return nil
			})
		case "singularMessage":
			if d.Next() == jx.Null {
				return d.Null()
			}
			m.SingularMessage = &ScalarTypes{}
			return m.SingularMessage.Decode(d)
		case "optionalMessage":
			if d.Next() == jx.Null {
				return d.Null()
			}
			m.OptionalMessage = &ScalarTypes{}
			return m.OptionalMessage.Decode(d)
		case "repeatedMessage":
			if d.Next() == jx.Null {
				return d.Null()
			}
			return d.Arr(func(d *jx.Decoder) error {
				el := &ScalarTypes{}
				if err := el.Decode(d); err != nil {
					return err
				}
				m.RepeatedMessage = append(m.RepeatedMessage, el)
				return nil
			})
		case "nestedEnum":
			switch d.Next() {
			case jx.String:
				s, err := d.Str()
				if err != nil {
					return err
				}
				n, ok := Outer_NestedEnum_value[s]
				if !ok {
					return fmt.Errorf("unknown enum value %q", s)
				}
				m.NestedEnum = Outer_NestedEnum(n)
				return nil
			case jx.Number:
				n, err := d.Int32()
				if err != nil {
					return err
				}
				m.NestedEnum = Outer_NestedEnum(n)
				return nil
			case jx.Null:
				return d.Null()
			default:
				return fmt.Errorf("invalid enum token %s", d.Next())
			}
		case "nestedMessage":
			if d.Next() == jx.Null {
				return d.Null()
			}
			m.NestedMessage = &Outer_Inner{}
			return m.NestedMessage.Decode(d)
		default:
			return fmt.Errorf("unknown field %q", key)
		}
	})
}

func (m *EnumAndMessageFields) MarshalJSON() ([]byte, error) {
	var e jx.Encoder
	m.Encode(&e)
	return e.Bytes(), nil
}

func (m *EnumAndMessageFields) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return m.Decode(d)
}

func (m *MapKeyTypes) Encode(e *jx.Encoder) {
	if m == nil {
		e.ObjStart()
		e.ObjEnd()
		return
	}
	e.ObjStart()
	if len(m.Int32Key) > 0 {
		e.FieldStart("int32Key")
		e.ObjStart()
		for k, v := range m.Int32Key {
			e.FieldStart(strconv.FormatInt(int64(k), 10))
			e.Str(v)
		}
		e.ObjEnd()
	}
	if len(m.Int64Key) > 0 {
		e.FieldStart("int64Key")
		e.ObjStart()
		for k, v := range m.Int64Key {
			e.FieldStart(strconv.FormatInt(k, 10))
			e.Str(v)
		}
		e.ObjEnd()
	}
	if len(m.Uint32Key) > 0 {
		e.FieldStart("uint32Key")
		e.ObjStart()
		for k, v := range m.Uint32Key {
			e.FieldStart(strconv.FormatInt(int64(k), 10))
			e.Str(v)
		}
		e.ObjEnd()
	}
	if len(m.Uint64Key) > 0 {
		e.FieldStart("uint64Key")
		e.ObjStart()
		for k, v := range m.Uint64Key {
			e.FieldStart(strconv.FormatUint(k, 10))
			e.Str(v)
		}
		e.ObjEnd()
	}
	if len(m.Sint32Key) > 0 {
		e.FieldStart("sint32Key")
		e.ObjStart()
		for k, v := range m.Sint32Key {
			e.FieldStart(strconv.FormatInt(int64(k), 10))
			e.Str(v)
		}
		e.ObjEnd()
	}
	if len(m.Sint64Key) > 0 {
		e.FieldStart("sint64Key")
		e.ObjStart()
		for k, v := range m.Sint64Key {
			e.FieldStart(strconv.FormatInt(k, 10))
			e.Str(v)
		}
		e.ObjEnd()
	}
	if len(m.Fixed32Key) > 0 {
		e.FieldStart("fixed32Key")
		e.ObjStart()
		for k, v := range m.Fixed32Key {
			e.FieldStart(strconv.FormatInt(int64(k), 10))
			e.Str(v)
		}
		e.ObjEnd()
	}
	if len(m.Fixed64Key) > 0 {
		e.FieldStart("fixed64Key")
		e.ObjStart()
		for k, v := range m.Fixed64Key {
			e.FieldStart(strconv.FormatUint(k, 10))
			e.Str(v)
		}
		e.ObjEnd()
	}
	if len(m.Sfixed32Key) > 0 {
		e.FieldStart("sfixed32Key")
		e.ObjStart()
		for k, v := range m.Sfixed32Key {
			e.FieldStart(strconv.FormatInt(int64(k), 10))
			e.Str(v)
		}
		e.ObjEnd()
	}
	if len(m.Sfixed64Key) > 0 {
		e.FieldStart("sfixed64Key")
		e.ObjStart()
		for k, v := range m.Sfixed64Key {
			e.FieldStart(strconv.FormatInt(k, 10))
			e.Str(v)
		}
		e.ObjEnd()
	}
	if len(m.BoolKey) > 0 {
		e.FieldStart("boolKey")
		e.ObjStart()
		for k, v := range m.BoolKey {
			e.FieldStart(strconv.FormatBool(k))
			e.Str(v)
		}
		e.ObjEnd()
	}
	if len(m.StringKey) > 0 {
		e.FieldStart("stringKey")
		e.ObjStart()
		for k, v := range m.StringKey {
			e.FieldStart(k)
			e.Str(v)
		}
		e.ObjEnd()
	}
	e.ObjEnd()
}

func (m *MapKeyTypes) Decode(d *jx.Decoder) error {
	return d.Obj(func(d *jx.Decoder, key string) error {
		switch key {
		case "int32Key":
			if d.Next() == jx.Null {
				return d.Null()
			}
			if m.Int32Key == nil {
				m.Int32Key = make(map[int32]string)
			}
			return d.Obj(func(d *jx.Decoder, ks string) error {
				mk64, err := strconv.ParseInt(ks, 10, 32)
				if err != nil {
					return err
				}
				mk := int32(mk64)
				var mv string
				tv, err := d.Str()
				if err != nil {
					return err
				}
				mv = tv
				m.Int32Key[mk] = mv
				return nil
			})
		case "int64Key":
			if d.Next() == jx.Null {
				return d.Null()
			}
			if m.Int64Key == nil {
				m.Int64Key = make(map[int64]string)
			}
			return d.Obj(func(d *jx.Decoder, ks string) error {
				mk, err := strconv.ParseInt(ks, 10, 64)
				if err != nil {
					return err
				}
				var mv string
				tv, err := d.Str()
				if err != nil {
					return err
				}
				mv = tv
				m.Int64Key[mk] = mv
				return nil
			})
		case "uint32Key":
			if d.Next() == jx.Null {
				return d.Null()
			}
			if m.Uint32Key == nil {
				m.Uint32Key = make(map[uint32]string)
			}
			return d.Obj(func(d *jx.Decoder, ks string) error {
				mk64, err := strconv.ParseUint(ks, 10, 32)
				if err != nil {
					return err
				}
				mk := uint32(mk64)
				var mv string
				tv, err := d.Str()
				if err != nil {
					return err
				}
				mv = tv
				m.Uint32Key[mk] = mv
				return nil
			})
		case "uint64Key":
			if d.Next() == jx.Null {
				return d.Null()
			}
			if m.Uint64Key == nil {
				m.Uint64Key = make(map[uint64]string)
			}
			return d.Obj(func(d *jx.Decoder, ks string) error {
				mk, err := strconv.ParseUint(ks, 10, 64)
				if err != nil {
					return err
				}
				var mv string
				tv, err := d.Str()
				if err != nil {
					return err
				}
				mv = tv
				m.Uint64Key[mk] = mv
				return nil
			})
		case "sint32Key":
			if d.Next() == jx.Null {
				return d.Null()
			}
			if m.Sint32Key == nil {
				m.Sint32Key = make(map[int32]string)
			}
			return d.Obj(func(d *jx.Decoder, ks string) error {
				mk64, err := strconv.ParseInt(ks, 10, 32)
				if err != nil {
					return err
				}
				mk := int32(mk64)
				var mv string
				tv, err := d.Str()
				if err != nil {
					return err
				}
				mv = tv
				m.Sint32Key[mk] = mv
				return nil
			})
		case "sint64Key":
			if d.Next() == jx.Null {
				return d.Null()
			}
			if m.Sint64Key == nil {
				m.Sint64Key = make(map[int64]string)
			}
			return d.Obj(func(d *jx.Decoder, ks string) error {
				mk, err := strconv.ParseInt(ks, 10, 64)
				if err != nil {
					return err
				}
				var mv string
				tv, err := d.Str()
				if err != nil {
					return err
				}
				mv = tv
				m.Sint64Key[mk] = mv
				return nil
			})
		case "fixed32Key":
			if d.Next() == jx.Null {
				return d.Null()
			}
			if m.Fixed32Key == nil {
				m.Fixed32Key = make(map[uint32]string)
			}
			return d.Obj(func(d *jx.Decoder, ks string) error {
				mk64, err := strconv.ParseUint(ks, 10, 32)
				if err != nil {
					return err
				}
				mk := uint32(mk64)
				var mv string
				tv, err := d.Str()
				if err != nil {
					return err
				}
				mv = tv
				m.Fixed32Key[mk] = mv
				return nil
			})
		case "fixed64Key":
			if d.Next() == jx.Null {
				return d.Null()
			}
			if m.Fixed64Key == nil {
				m.Fixed64Key = make(map[uint64]string)
			}
			return d.Obj(func(d *jx.Decoder, ks string) error {
				mk, err := strconv.ParseUint(ks, 10, 64)
				if err != nil {
					return err
				}
				var mv string
				tv, err := d.Str()
				if err != nil {
					return err
				}
				mv = tv
				m.Fixed64Key[mk] = mv
				return nil
			})
		case "sfixed32Key":
			if d.Next() == jx.Null {
				return d.Null()
			}
			if m.Sfixed32Key == nil {
				m.Sfixed32Key = make(map[int32]string)
			}
			return d.Obj(func(d *jx.Decoder, ks string) error {
				mk64, err := strconv.ParseInt(ks, 10, 32)
				if err != nil {
					return err
				}
				mk := int32(mk64)
				var mv string
				tv, err := d.Str()
				if err != nil {
					return err
				}
				mv = tv
				m.Sfixed32Key[mk] = mv
				return nil
			})
		case "sfixed64Key":
			if d.Next() == jx.Null {
				return d.Null()
			}
			if m.Sfixed64Key == nil {
				m.Sfixed64Key = make(map[int64]string)
			}
			return d.Obj(func(d *jx.Decoder, ks string) error {
				mk, err := strconv.ParseInt(ks, 10, 64)
				if err != nil {
					return err
				}
				var mv string
				tv, err := d.Str()
				if err != nil {
					return err
				}
				mv = tv
				m.Sfixed64Key[mk] = mv
				return nil
			})
		case "boolKey":
			if d.Next() == jx.Null {
				return d.Null()
			}
			if m.BoolKey == nil {
				m.BoolKey = make(map[bool]string)
			}
			return d.Obj(func(d *jx.Decoder, ks string) error {
				mk, err := strconv.ParseBool(ks)
				if err != nil {
					return err
				}
				var mv string
				tv, err := d.Str()
				if err != nil {
					return err
				}
				mv = tv
				m.BoolKey[mk] = mv
				return nil
			})
		case "stringKey":
			if d.Next() == jx.Null {
				return d.Null()
			}
			if m.StringKey == nil {
				m.StringKey = make(map[string]string)
			}
			return d.Obj(func(d *jx.Decoder, ks string) error {
				mk := ks
				var mv string
				tv, err := d.Str()
				if err != nil {
					return err
				}
				mv = tv
				m.StringKey[mk] = mv
				return nil
			})
		default:
			return fmt.Errorf("unknown field %q", key)
		}
	})
}

func (m *MapKeyTypes) MarshalJSON() ([]byte, error) {
	var e jx.Encoder
	m.Encode(&e)
	return e.Bytes(), nil
}

func (m *MapKeyTypes) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return m.Decode(d)
}

func (m *MapValueTypes) Encode(e *jx.Encoder) {
	if m == nil {
		e.ObjStart()
		e.ObjEnd()
		return
	}
	e.ObjStart()
	if len(m.DoubleValue) > 0 {
		e.FieldStart("doubleValue")
		e.ObjStart()
		for k, v := range m.DoubleValue {
			e.FieldStart(k)
			jxpb.EncFloat64(e, v)
		}
		e.ObjEnd()
	}
	if len(m.FloatValue) > 0 {
		e.FieldStart("floatValue")
		e.ObjStart()
		for k, v := range m.FloatValue {
			e.FieldStart(k)
			jxpb.EncFloat32(e, v)
		}
		e.ObjEnd()
	}
	if len(m.Int32Value) > 0 {
		e.FieldStart("int32Value")
		e.ObjStart()
		for k, v := range m.Int32Value {
			e.FieldStart(k)
			e.Int32(v)
		}
		e.ObjEnd()
	}
	if len(m.Int64Value) > 0 {
		e.FieldStart("int64Value")
		e.ObjStart()
		for k, v := range m.Int64Value {
			e.FieldStart(k)
			jxpb.EncInt64(e, v)
		}
		e.ObjEnd()
	}
	if len(m.Uint32Value) > 0 {
		e.FieldStart("uint32Value")
		e.ObjStart()
		for k, v := range m.Uint32Value {
			e.FieldStart(k)
			e.UInt32(v)
		}
		e.ObjEnd()
	}
	if len(m.Uint64Value) > 0 {
		e.FieldStart("uint64Value")
		e.ObjStart()
		for k, v := range m.Uint64Value {
			e.FieldStart(k)
			jxpb.EncUint64(e, v)
		}
		e.ObjEnd()
	}
	if len(m.BoolValue) > 0 {
		e.FieldStart("boolValue")
		e.ObjStart()
		for k, v := range m.BoolValue {
			e.FieldStart(k)
			e.Bool(v)
		}
		e.ObjEnd()
	}
	if len(m.StringValue) > 0 {
		e.FieldStart("stringValue")
		e.ObjStart()
		for k, v := range m.StringValue {
			e.FieldStart(k)
			e.Str(v)
		}
		e.ObjEnd()
	}
	if len(m.BytesValue) > 0 {
		e.FieldStart("bytesValue")
		e.ObjStart()
		for k, v := range m.BytesValue {
			e.FieldStart(k)
			jxpb.EncBytes(e, v)
		}
		e.ObjEnd()
	}
	if len(m.EnumValue) > 0 {
		e.FieldStart("enumValue")
		e.ObjStart()
		for k, v := range m.EnumValue {
			e.FieldStart(k)
			if s, ok := TopLevelEnum_name[int32(v)]; ok {
				e.Str(s)
			} else {
				e.Int32(int32(v))
			}
		}
		e.ObjEnd()
	}
	if len(m.MessageValue) > 0 {
		e.FieldStart("messageValue")
		e.ObjStart()
		for k, v := range m.MessageValue {
			e.FieldStart(k)
			v.Encode(e)
		}
		e.ObjEnd()
	}
	e.ObjEnd()
}

func (m *MapValueTypes) Decode(d *jx.Decoder) error {
	return d.Obj(func(d *jx.Decoder, key string) error {
		switch key {
		case "doubleValue":
			if d.Next() == jx.Null {
				return d.Null()
			}
			if m.DoubleValue == nil {
				m.DoubleValue = make(map[string]float64)
			}
			return d.Obj(func(d *jx.Decoder, ks string) error {
				mk := ks
				var mv float64
				tv, err := jxpb.DecFloat64(d)
				if err != nil {
					return err
				}
				mv = tv
				m.DoubleValue[mk] = mv
				return nil
			})
		case "floatValue":
			if d.Next() == jx.Null {
				return d.Null()
			}
			if m.FloatValue == nil {
				m.FloatValue = make(map[string]float32)
			}
			return d.Obj(func(d *jx.Decoder, ks string) error {
				mk := ks
				var mv float32
				tv, err := jxpb.DecFloat32(d)
				if err != nil {
					return err
				}
				mv = tv
				m.FloatValue[mk] = mv
				return nil
			})
		case "int32Value":
			if d.Next() == jx.Null {
				return d.Null()
			}
			if m.Int32Value == nil {
				m.Int32Value = make(map[string]int32)
			}
			return d.Obj(func(d *jx.Decoder, ks string) error {
				mk := ks
				var mv int32
				tv, err := jxpb.DecInt32(d)
				if err != nil {
					return err
				}
				mv = tv
				m.Int32Value[mk] = mv
				return nil
			})
		case "int64Value":
			if d.Next() == jx.Null {
				return d.Null()
			}
			if m.Int64Value == nil {
				m.Int64Value = make(map[string]int64)
			}
			return d.Obj(func(d *jx.Decoder, ks string) error {
				mk := ks
				var mv int64
				tv, err := jxpb.DecInt64(d)
				if err != nil {
					return err
				}
				mv = tv
				m.Int64Value[mk] = mv
				return nil
			})
		case "uint32Value":
			if d.Next() == jx.Null {
				return d.Null()
			}
			if m.Uint32Value == nil {
				m.Uint32Value = make(map[string]uint32)
			}
			return d.Obj(func(d *jx.Decoder, ks string) error {
				mk := ks
				var mv uint32
				tv, err := jxpb.DecUint32(d)
				if err != nil {
					return err
				}
				mv = tv
				m.Uint32Value[mk] = mv
				return nil
			})
		case "uint64Value":
			if d.Next() == jx.Null {
				return d.Null()
			}
			if m.Uint64Value == nil {
				m.Uint64Value = make(map[string]uint64)
			}
			return d.Obj(func(d *jx.Decoder, ks string) error {
				mk := ks
				var mv uint64
				tv, err := jxpb.DecUint64(d)
				if err != nil {
					return err
				}
				mv = tv
				m.Uint64Value[mk] = mv
				return nil
			})
		case "boolValue":
			if d.Next() == jx.Null {
				return d.Null()
			}
			if m.BoolValue == nil {
				m.BoolValue = make(map[string]bool)
			}
			return d.Obj(func(d *jx.Decoder, ks string) error {
				mk := ks
				var mv bool
				tv, err := d.Bool()
				if err != nil {
					return err
				}
				mv = tv
				m.BoolValue[mk] = mv
				return nil
			})
		case "stringValue":
			if d.Next() == jx.Null {
				return d.Null()
			}
			if m.StringValue == nil {
				m.StringValue = make(map[string]string)
			}
			return d.Obj(func(d *jx.Decoder, ks string) error {
				mk := ks
				var mv string
				tv, err := d.Str()
				if err != nil {
					return err
				}
				mv = tv
				m.StringValue[mk] = mv
				return nil
			})
		case "bytesValue":
			if d.Next() == jx.Null {
				return d.Null()
			}
			if m.BytesValue == nil {
				m.BytesValue = make(map[string][]byte)
			}
			return d.Obj(func(d *jx.Decoder, ks string) error {
				mk := ks
				var mv []byte
				tv, err := jxpb.DecBytes(d)
				if err != nil {
					return err
				}
				mv = tv
				m.BytesValue[mk] = mv
				return nil
			})
		case "enumValue":
			if d.Next() == jx.Null {
				return d.Null()
			}
			if m.EnumValue == nil {
				m.EnumValue = make(map[string]TopLevelEnum)
			}
			return d.Obj(func(d *jx.Decoder, ks string) error {
				mk := ks
				var mv TopLevelEnum
				switch d.Next() {
				case jx.String:
					s, err := d.Str()
					if err != nil {
						return err
					}
					n, ok := TopLevelEnum_value[s]
					if !ok {
						return fmt.Errorf("unknown enum value %q", s)
					}
					mv = TopLevelEnum(n)
				default:
					n, err := d.Int32()
					if err != nil {
						return err
					}
					mv = TopLevelEnum(n)
				}
				m.EnumValue[mk] = mv
				return nil
			})
		case "messageValue":
			if d.Next() == jx.Null {
				return d.Null()
			}
			if m.MessageValue == nil {
				m.MessageValue = make(map[string]*ScalarTypes)
			}
			return d.Obj(func(d *jx.Decoder, ks string) error {
				mk := ks
				var mv *ScalarTypes
				mv = &ScalarTypes{}
				if err := mv.Decode(d); err != nil {
					return err
				}
				m.MessageValue[mk] = mv
				return nil
			})
		default:
			return fmt.Errorf("unknown field %q", key)
		}
	})
}

func (m *MapValueTypes) MarshalJSON() ([]byte, error) {
	var e jx.Encoder
	m.Encode(&e)
	return e.Bytes(), nil
}

func (m *MapValueTypes) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return m.Decode(d)
}

func (m *OneofContainer) Encode(e *jx.Encoder) {
	if m == nil {
		e.ObjStart()
		e.ObjEnd()
		return
	}
	e.ObjStart()
	if m.OutsideOneof != "" {
		e.FieldStart("outsideOneof")
		e.Str(m.OutsideOneof)
	}
	switch v := m.Choice.(type) {
	case *OneofContainer_ChoiceDouble:
		e.FieldStart("choiceDouble")
		jxpb.EncFloat64(e, v.ChoiceDouble)
	case *OneofContainer_ChoiceInt32:
		e.FieldStart("choiceInt32")
		e.Int32(v.ChoiceInt32)
	case *OneofContainer_ChoiceBool:
		e.FieldStart("choiceBool")
		e.Bool(v.ChoiceBool)
	case *OneofContainer_ChoiceString:
		e.FieldStart("choiceString")
		e.Str(v.ChoiceString)
	case *OneofContainer_ChoiceBytes:
		e.FieldStart("choiceBytes")
		jxpb.EncBytes(e, v.ChoiceBytes)
	case *OneofContainer_ChoiceEnum:
		e.FieldStart("choiceEnum")
		if s, ok := TopLevelEnum_name[int32(v.ChoiceEnum)]; ok {
			e.Str(s)
		} else {
			e.Int32(int32(v.ChoiceEnum))
		}
	case *OneofContainer_ChoiceMessage:
		e.FieldStart("choiceMessage")
		v.ChoiceMessage.Encode(e)
	}
	switch v := m.Other.(type) {
	case *OneofContainer_OtherA:
		e.FieldStart("otherA")
		e.Str(v.OtherA)
	case *OneofContainer_OtherB:
		e.FieldStart("otherB")
		jxpb.EncInt64(e, v.OtherB)
	}
	e.ObjEnd()
}

func (m *OneofContainer) Decode(d *jx.Decoder) error {
	return d.Obj(func(d *jx.Decoder, key string) error {
		switch key {
		case "outsideOneof":
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := d.Str()
			if err != nil {
				return err
			}
			m.OutsideOneof = v
			return nil
		case "choiceDouble":
			if d.Next() == jx.Null {
				return d.Null()
			}
			val, err := jxpb.DecFloat64(d)
			if err != nil {
				return err
			}
			m.Choice = &OneofContainer_ChoiceDouble{ChoiceDouble: val}
			return nil
		case "choiceInt32":
			if d.Next() == jx.Null {
				return d.Null()
			}
			val, err := jxpb.DecInt32(d)
			if err != nil {
				return err
			}
			m.Choice = &OneofContainer_ChoiceInt32{ChoiceInt32: val}
			return nil
		case "choiceBool":
			if d.Next() == jx.Null {
				return d.Null()
			}
			val, err := d.Bool()
			if err != nil {
				return err
			}
			m.Choice = &OneofContainer_ChoiceBool{ChoiceBool: val}
			return nil
		case "choiceString":
			if d.Next() == jx.Null {
				return d.Null()
			}
			val, err := d.Str()
			if err != nil {
				return err
			}
			m.Choice = &OneofContainer_ChoiceString{ChoiceString: val}
			return nil
		case "choiceBytes":
			if d.Next() == jx.Null {
				return d.Null()
			}
			val, err := jxpb.DecBytes(d)
			if err != nil {
				return err
			}
			m.Choice = &OneofContainer_ChoiceBytes{ChoiceBytes: val}
			return nil
		case "choiceEnum":
			if d.Next() == jx.Null {
				return d.Null()
			}
			w := &OneofContainer_ChoiceEnum{}
			switch d.Next() {
			case jx.String:
				s, err := d.Str()
				if err != nil {
					return err
				}
				n, ok := TopLevelEnum_value[s]
				if !ok {
					return fmt.Errorf("unknown enum value %q", s)
				}
				w.ChoiceEnum = TopLevelEnum(n)
			default:
				n, err := d.Int32()
				if err != nil {
					return err
				}
				w.ChoiceEnum = TopLevelEnum(n)
			}
			m.Choice = w
			return nil
		case "choiceMessage":
			if d.Next() == jx.Null {
				return d.Null()
			}
			w := &OneofContainer_ChoiceMessage{}
			w.ChoiceMessage = &ScalarTypes{}
			if err := w.ChoiceMessage.Decode(d); err != nil {
				return err
			}
			m.Choice = w
			return nil
		case "otherA":
			if d.Next() == jx.Null {
				return d.Null()
			}
			val, err := d.Str()
			if err != nil {
				return err
			}
			m.Other = &OneofContainer_OtherA{OtherA: val}
			return nil
		case "otherB":
			if d.Next() == jx.Null {
				return d.Null()
			}
			val, err := jxpb.DecInt64(d)
			if err != nil {
				return err
			}
			m.Other = &OneofContainer_OtherB{OtherB: val}
			return nil
		default:
			return fmt.Errorf("unknown field %q", key)
		}
	})
}

func (m *OneofContainer) MarshalJSON() ([]byte, error) {
	var e jx.Encoder
	m.Encode(&e)
	return e.Bytes(), nil
}

func (m *OneofContainer) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return m.Decode(d)
}

func (m *WellKnownTypes) Encode(e *jx.Encoder) {
	if m == nil {
		e.ObjStart()
		e.ObjEnd()
		return
	}
	e.ObjStart()
	e.ObjEnd()
}

func (m *WellKnownTypes) Decode(d *jx.Decoder) error {
	return d.Obj(func(d *jx.Decoder, key string) error {
		switch key {
		default:
			return fmt.Errorf("unknown field %q", key)
		}
	})
}

func (m *WellKnownTypes) MarshalJSON() ([]byte, error) {
	var e jx.Encoder
	m.Encode(&e)
	return e.Bytes(), nil
}

func (m *WellKnownTypes) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return m.Decode(d)
}

func (m *TreeNode) Encode(e *jx.Encoder) {
	if m == nil {
		e.ObjStart()
		e.ObjEnd()
		return
	}
	e.ObjStart()
	if m.Id != "" {
		e.FieldStart("id")
		e.Str(m.Id)
	}
	if m.Parent != nil {
		e.FieldStart("parent")
		m.Parent.Encode(e)
	}
	if len(m.Children) > 0 {
		e.FieldStart("children")
		e.ArrStart()
		for _, v := range m.Children {
			v.Encode(e)
		}
		e.ArrEnd()
	}
	if len(m.Named) > 0 {
		e.FieldStart("named")
		e.ObjStart()
		for k, v := range m.Named {
			e.FieldStart(k)
			v.Encode(e)
		}
		e.ObjEnd()
	}
	e.ObjEnd()
}

func (m *TreeNode) Decode(d *jx.Decoder) error {
	return d.Obj(func(d *jx.Decoder, key string) error {
		switch key {
		case "id":
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := d.Str()
			if err != nil {
				return err
			}
			m.Id = v
			return nil
		case "parent":
			if d.Next() == jx.Null {
				return d.Null()
			}
			m.Parent = &TreeNode{}
			return m.Parent.Decode(d)
		case "children":
			if d.Next() == jx.Null {
				return d.Null()
			}
			return d.Arr(func(d *jx.Decoder) error {
				el := &TreeNode{}
				if err := el.Decode(d); err != nil {
					return err
				}
				m.Children = append(m.Children, el)
				return nil
			})
		case "named":
			if d.Next() == jx.Null {
				return d.Null()
			}
			if m.Named == nil {
				m.Named = make(map[string]*TreeNode)
			}
			return d.Obj(func(d *jx.Decoder, ks string) error {
				mk := ks
				var mv *TreeNode
				mv = &TreeNode{}
				if err := mv.Decode(d); err != nil {
					return err
				}
				m.Named[mk] = mv
				return nil
			})
		default:
			return fmt.Errorf("unknown field %q", key)
		}
	})
}

func (m *TreeNode) MarshalJSON() ([]byte, error) {
	var e jx.Encoder
	m.Encode(&e)
	return e.Bytes(), nil
}

func (m *TreeNode) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return m.Decode(d)
}

func (m *MutualA) Encode(e *jx.Encoder) {
	if m == nil {
		e.ObjStart()
		e.ObjEnd()
		return
	}
	e.ObjStart()
	if m.B != nil {
		e.FieldStart("b")
		m.B.Encode(e)
	}
	e.ObjEnd()
}

func (m *MutualA) Decode(d *jx.Decoder) error {
	return d.Obj(func(d *jx.Decoder, key string) error {
		switch key {
		case "b":
			if d.Next() == jx.Null {
				return d.Null()
			}
			m.B = &MutualB{}
			return m.B.Decode(d)
		default:
			return fmt.Errorf("unknown field %q", key)
		}
	})
}

func (m *MutualA) MarshalJSON() ([]byte, error) {
	var e jx.Encoder
	m.Encode(&e)
	return e.Bytes(), nil
}

func (m *MutualA) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return m.Decode(d)
}

func (m *MutualB) Encode(e *jx.Encoder) {
	if m == nil {
		e.ObjStart()
		e.ObjEnd()
		return
	}
	e.ObjStart()
	if m.A != nil {
		e.FieldStart("a")
		m.A.Encode(e)
	}
	e.ObjEnd()
}

func (m *MutualB) Decode(d *jx.Decoder) error {
	return d.Obj(func(d *jx.Decoder, key string) error {
		switch key {
		case "a":
			if d.Next() == jx.Null {
				return d.Null()
			}
			m.A = &MutualA{}
			return m.A.Decode(d)
		default:
			return fmt.Errorf("unknown field %q", key)
		}
	})
}

func (m *MutualB) MarshalJSON() ([]byte, error) {
	var e jx.Encoder
	m.Encode(&e)
	return e.Bytes(), nil
}

func (m *MutualB) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return m.Decode(d)
}

func (m *Reserved) Encode(e *jx.Encoder) {
	if m == nil {
		e.ObjStart()
		e.ObjEnd()
		return
	}
	e.ObjStart()
	if m.Active != "" {
		e.FieldStart("active")
		e.Str(m.Active)
	}
	e.ObjEnd()
}

func (m *Reserved) Decode(d *jx.Decoder) error {
	return d.Obj(func(d *jx.Decoder, key string) error {
		switch key {
		case "active":
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := d.Str()
			if err != nil {
				return err
			}
			m.Active = v
			return nil
		default:
			return fmt.Errorf("unknown field %q", key)
		}
	})
}

func (m *Reserved) MarshalJSON() ([]byte, error) {
	var e jx.Encoder
	m.Encode(&e)
	return e.Bytes(), nil
}

func (m *Reserved) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return m.Decode(d)
}

func (m *Everything) Encode(e *jx.Encoder) {
	if m == nil {
		e.ObjStart()
		e.ObjEnd()
		return
	}
	e.ObjStart()
	if m.Scalars != nil {
		e.FieldStart("scalars")
		m.Scalars.Encode(e)
	}
	if m.Optionals != nil {
		e.FieldStart("optionals")
		m.Optionals.Encode(e)
	}
	if m.Repeateds != nil {
		e.FieldStart("repeateds")
		m.Repeateds.Encode(e)
	}
	if m.EnumsAndMessages != nil {
		e.FieldStart("enumsAndMessages")
		m.EnumsAndMessages.Encode(e)
	}
	if m.MapKeys != nil {
		e.FieldStart("mapKeys")
		m.MapKeys.Encode(e)
	}
	if m.MapValues != nil {
		e.FieldStart("mapValues")
		m.MapValues.Encode(e)
	}
	if m.Oneof != nil {
		e.FieldStart("oneof")
		m.Oneof.Encode(e)
	}
	if m.WellKnown != nil {
		e.FieldStart("wellKnown")
		m.WellKnown.Encode(e)
	}
	if m.Tree != nil {
		e.FieldStart("tree")
		m.Tree.Encode(e)
	}
	if m.Reserved != nil {
		e.FieldStart("reserved")
		m.Reserved.Encode(e)
	}
	if len(m.Recursive) > 0 {
		e.FieldStart("recursive")
		e.ArrStart()
		for _, v := range m.Recursive {
			v.Encode(e)
		}
		e.ArrEnd()
	}
	switch v := m.Terminal.(type) {
	case *Everything_Done:
		e.FieldStart("done")
		e.Bool(v.Done)
	case *Everything_Error:
		e.FieldStart("error")
		e.Str(v.Error)
	}
	e.ObjEnd()
}

func (m *Everything) Decode(d *jx.Decoder) error {
	return d.Obj(func(d *jx.Decoder, key string) error {
		switch key {
		case "scalars":
			if d.Next() == jx.Null {
				return d.Null()
			}
			m.Scalars = &ScalarTypes{}
			return m.Scalars.Decode(d)
		case "optionals":
			if d.Next() == jx.Null {
				return d.Null()
			}
			m.Optionals = &OptionalScalarTypes{}
			return m.Optionals.Decode(d)
		case "repeateds":
			if d.Next() == jx.Null {
				return d.Null()
			}
			m.Repeateds = &RepeatedScalarTypes{}
			return m.Repeateds.Decode(d)
		case "enumsAndMessages":
			if d.Next() == jx.Null {
				return d.Null()
			}
			m.EnumsAndMessages = &EnumAndMessageFields{}
			return m.EnumsAndMessages.Decode(d)
		case "mapKeys":
			if d.Next() == jx.Null {
				return d.Null()
			}
			m.MapKeys = &MapKeyTypes{}
			return m.MapKeys.Decode(d)
		case "mapValues":
			if d.Next() == jx.Null {
				return d.Null()
			}
			m.MapValues = &MapValueTypes{}
			return m.MapValues.Decode(d)
		case "oneof":
			if d.Next() == jx.Null {
				return d.Null()
			}
			m.Oneof = &OneofContainer{}
			return m.Oneof.Decode(d)
		case "wellKnown":
			if d.Next() == jx.Null {
				return d.Null()
			}
			m.WellKnown = &WellKnownTypes{}
			return m.WellKnown.Decode(d)
		case "tree":
			if d.Next() == jx.Null {
				return d.Null()
			}
			m.Tree = &TreeNode{}
			return m.Tree.Decode(d)
		case "reserved":
			if d.Next() == jx.Null {
				return d.Null()
			}
			m.Reserved = &Reserved{}
			return m.Reserved.Decode(d)
		case "recursive":
			if d.Next() == jx.Null {
				return d.Null()
			}
			return d.Arr(func(d *jx.Decoder) error {
				el := &Everything{}
				if err := el.Decode(d); err != nil {
					return err
				}
				m.Recursive = append(m.Recursive, el)
				return nil
			})
		case "done":
			if d.Next() == jx.Null {
				return d.Null()
			}
			val, err := d.Bool()
			if err != nil {
				return err
			}
			m.Terminal = &Everything_Done{Done: val}
			return nil
		case "error":
			if d.Next() == jx.Null {
				return d.Null()
			}
			val, err := d.Str()
			if err != nil {
				return err
			}
			m.Terminal = &Everything_Error{Error: val}
			return nil
		default:
			return fmt.Errorf("unknown field %q", key)
		}
	})
}

func (m *Everything) MarshalJSON() ([]byte, error) {
	var e jx.Encoder
	m.Encode(&e)
	return e.Bytes(), nil
}

func (m *Everything) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return m.Decode(d)
}
