// Code generated by protoc-gen-go-jx. DO NOT EDIT.

package golden

import (
	fmt "fmt"
	jx "github.com/go-faster/jx"
	jxpb "github.com/gopherex/protoc-gen-go-jx/jxpb"
	anypb "google.golang.org/protobuf/types/known/anypb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	math "math"
	strconv "strconv"
)

func (m *ScalarTypes) Encode(e *jx.Encoder) {
	if m == nil {
		e.ObjStart()
		e.ObjEnd()
		return
	}
	e.ObjStart()
	if m.FieldDouble != 0 || math.Signbit(float64(m.FieldDouble)) {
		e.FieldStart("fieldDouble")
		jxpb.EncFloat64(e, m.FieldDouble)
	}
	if m.FieldFloat != 0 || math.Signbit(float64(m.FieldFloat)) {
		e.FieldStart("fieldFloat")
		jxpb.EncFloat32(e, m.FieldFloat)
	}
	if m.FieldInt32 != 0 {
		e.FieldStart("fieldInt32")
		e.Int32(m.FieldInt32)
	}
	if m.FieldInt64 != 0 {
		e.FieldStart("fieldInt64")
		jxpb.EncInt64(e, m.FieldInt64)
	}
	if m.FieldUint32 != 0 {
		e.FieldStart("fieldUint32")
		e.UInt32(m.FieldUint32)
	}
	if m.FieldUint64 != 0 {
		e.FieldStart("fieldUint64")
		jxpb.EncUint64(e, m.FieldUint64)
	}
	if m.FieldSint32 != 0 {
		e.FieldStart("fieldSint32")
		e.Int32(m.FieldSint32)
	}
	if m.FieldSint64 != 0 {
		e.FieldStart("fieldSint64")
		jxpb.EncInt64(e, m.FieldSint64)
	}
	if m.FieldFixed32 != 0 {
		e.FieldStart("fieldFixed32")
		e.UInt32(m.FieldFixed32)
	}
	if m.FieldFixed64 != 0 {
		e.FieldStart("fieldFixed64")
		jxpb.EncUint64(e, m.FieldFixed64)
	}
	if m.FieldSfixed32 != 0 {
		e.FieldStart("fieldSfixed32")
		e.Int32(m.FieldSfixed32)
	}
	if m.FieldSfixed64 != 0 {
		e.FieldStart("fieldSfixed64")
		jxpb.EncInt64(e, m.FieldSfixed64)
	}
	if m.FieldBool != false {
		e.FieldStart("fieldBool")
		e.Bool(m.FieldBool)
	}
	if m.FieldString != "" {
		e.FieldStart("fieldString")
		e.Str(m.FieldString)
	}
	if len(m.FieldBytes) > 0 {
		e.FieldStart("fieldBytes")
		jxpb.EncBytes(e, m.FieldBytes)
	}
	e.ObjEnd()
}

func (m *ScalarTypes) Decode(d *jx.Decoder) error {
	seen := map[string]bool{}
	return d.Obj(func(d *jx.Decoder, key string) error {
		switch key {
		case "fieldDouble", "field_double":
			if seen["FieldDouble"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["FieldDouble"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := jxpb.DecFloat64(d)
			if err != nil {
				return err
			}
			m.FieldDouble = v
			return nil
		case "fieldFloat", "field_float":
			if seen["FieldFloat"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["FieldFloat"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := jxpb.DecFloat32(d)
			if err != nil {
				return err
			}
			m.FieldFloat = v
			return nil
		case "fieldInt32", "field_int32":
			if seen["FieldInt32"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["FieldInt32"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := jxpb.DecInt32(d)
			if err != nil {
				return err
			}
			m.FieldInt32 = v
			return nil
		case "fieldInt64", "field_int64":
			if seen["FieldInt64"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["FieldInt64"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := jxpb.DecInt64(d)
			if err != nil {
				return err
			}
			m.FieldInt64 = v
			return nil
		case "fieldUint32", "field_uint32":
			if seen["FieldUint32"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["FieldUint32"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := jxpb.DecUint32(d)
			if err != nil {
				return err
			}
			m.FieldUint32 = v
			return nil
		case "fieldUint64", "field_uint64":
			if seen["FieldUint64"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["FieldUint64"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := jxpb.DecUint64(d)
			if err != nil {
				return err
			}
			m.FieldUint64 = v
			return nil
		case "fieldSint32", "field_sint32":
			if seen["FieldSint32"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["FieldSint32"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := jxpb.DecInt32(d)
			if err != nil {
				return err
			}
			m.FieldSint32 = v
			return nil
		case "fieldSint64", "field_sint64":
			if seen["FieldSint64"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["FieldSint64"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := jxpb.DecInt64(d)
			if err != nil {
				return err
			}
			m.FieldSint64 = v
			return nil
		case "fieldFixed32", "field_fixed32":
			if seen["FieldFixed32"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["FieldFixed32"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := jxpb.DecUint32(d)
			if err != nil {
				return err
			}
			m.FieldFixed32 = v
			return nil
		case "fieldFixed64", "field_fixed64":
			if seen["FieldFixed64"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["FieldFixed64"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := jxpb.DecUint64(d)
			if err != nil {
				return err
			}
			m.FieldFixed64 = v
			return nil
		case "fieldSfixed32", "field_sfixed32":
			if seen["FieldSfixed32"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["FieldSfixed32"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := jxpb.DecInt32(d)
			if err != nil {
				return err
			}
			m.FieldSfixed32 = v
			return nil
		case "fieldSfixed64", "field_sfixed64":
			if seen["FieldSfixed64"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["FieldSfixed64"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := jxpb.DecInt64(d)
			if err != nil {
				return err
			}
			m.FieldSfixed64 = v
			return nil
		case "fieldBool", "field_bool":
			if seen["FieldBool"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["FieldBool"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := d.Bool()
			if err != nil {
				return err
			}
			m.FieldBool = v
			return nil
		case "fieldString", "field_string":
			if seen["FieldString"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["FieldString"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := d.Str()
			if err != nil {
				return err
			}
			m.FieldString = v
			return nil
		case "fieldBytes", "field_bytes":
			if seen["FieldBytes"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["FieldBytes"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := jxpb.DecBytes(d)
			if err != nil {
				return err
			}
			m.FieldBytes = v
			return nil
		default:
			return fmt.Errorf("unknown field %q", key)
		}
	})
}

func (m *ScalarTypes) MarshalJSON() ([]byte, error) {
	var e jx.Encoder
	m.Encode(&e)
	return e.Bytes(), nil
}

func (m *ScalarTypes) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return m.Decode(d)
}

func (m *OptionalScalarTypes) Encode(e *jx.Encoder) {
	if m == nil {
		e.ObjStart()
		e.ObjEnd()
		return
	}
	e.ObjStart()
	if m.FieldDouble != nil {
		e.FieldStart("fieldDouble")
		jxpb.EncFloat64(e, *m.FieldDouble)
	}
	if m.FieldFloat != nil {
		e.FieldStart("fieldFloat")
		jxpb.EncFloat32(e, *m.FieldFloat)
	}
	if m.FieldInt32 != nil {
		e.FieldStart("fieldInt32")
		e.Int32(*m.FieldInt32)
	}
	if m.FieldInt64 != nil {
		e.FieldStart("fieldInt64")
		jxpb.EncInt64(e, *m.FieldInt64)
	}
	if m.FieldUint32 != nil {
		e.FieldStart("fieldUint32")
		e.UInt32(*m.FieldUint32)
	}
	if m.FieldUint64 != nil {
		e.FieldStart("fieldUint64")
		jxpb.EncUint64(e, *m.FieldUint64)
	}
	if m.FieldSint32 != nil {
		e.FieldStart("fieldSint32")
		e.Int32(*m.FieldSint32)
	}
	if m.FieldSint64 != nil {
		e.FieldStart("fieldSint64")
		jxpb.EncInt64(e, *m.FieldSint64)
	}
	if m.FieldFixed32 != nil {
		e.FieldStart("fieldFixed32")
		e.UInt32(*m.FieldFixed32)
	}
	if m.FieldFixed64 != nil {
		e.FieldStart("fieldFixed64")
		jxpb.EncUint64(e, *m.FieldFixed64)
	}
	if m.FieldSfixed32 != nil {
		e.FieldStart("fieldSfixed32")
		e.Int32(*m.FieldSfixed32)
	}
	if m.FieldSfixed64 != nil {
		e.FieldStart("fieldSfixed64")
		jxpb.EncInt64(e, *m.FieldSfixed64)
	}
	if m.FieldBool != nil {
		e.FieldStart("fieldBool")
		e.Bool(*m.FieldBool)
	}
	if m.FieldString != nil {
		e.FieldStart("fieldString")
		e.Str(*m.FieldString)
	}
	if len(m.FieldBytes) > 0 {
		e.FieldStart("fieldBytes")
		jxpb.EncBytes(e, m.FieldBytes)
	}
	e.ObjEnd()
}

func (m *OptionalScalarTypes) Decode(d *jx.Decoder) error {
	seen := map[string]bool{}
	return d.Obj(func(d *jx.Decoder, key string) error {
		switch key {
		case "fieldDouble", "field_double":
			if seen["FieldDouble"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["FieldDouble"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := jxpb.DecFloat64(d)
			if err != nil {
				return err
			}
			m.FieldDouble = &v
			return nil
		case "fieldFloat", "field_float":
			if seen["FieldFloat"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["FieldFloat"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := jxpb.DecFloat32(d)
			if err != nil {
				return err
			}
			m.FieldFloat = &v
			return nil
		case "fieldInt32", "field_int32":
			if seen["FieldInt32"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["FieldInt32"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := jxpb.DecInt32(d)
			if err != nil {
				return err
			}
			m.FieldInt32 = &v
			return nil
		case "fieldInt64", "field_int64":
			if seen["FieldInt64"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["FieldInt64"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := jxpb.DecInt64(d)
			if err != nil {
				return err
			}
			m.FieldInt64 = &v
			return nil
		case "fieldUint32", "field_uint32":
			if seen["FieldUint32"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["FieldUint32"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := jxpb.DecUint32(d)
			if err != nil {
				return err
			}
			m.FieldUint32 = &v
			return nil
		case "fieldUint64", "field_uint64":
			if seen["FieldUint64"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["FieldUint64"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := jxpb.DecUint64(d)
			if err != nil {
				return err
			}
			m.FieldUint64 = &v
			return nil
		case "fieldSint32", "field_sint32":
			if seen["FieldSint32"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["FieldSint32"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := jxpb.DecInt32(d)
			if err != nil {
				return err
			}
			m.FieldSint32 = &v
			return nil
		case "fieldSint64", "field_sint64":
			if seen["FieldSint64"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["FieldSint64"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := jxpb.DecInt64(d)
			if err != nil {
				return err
			}
			m.FieldSint64 = &v
			return nil
		case "fieldFixed32", "field_fixed32":
			if seen["FieldFixed32"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["FieldFixed32"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := jxpb.DecUint32(d)
			if err != nil {
				return err
			}
			m.FieldFixed32 = &v
			return nil
		case "fieldFixed64", "field_fixed64":
			if seen["FieldFixed64"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["FieldFixed64"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := jxpb.DecUint64(d)
			if err != nil {
				return err
			}
			m.FieldFixed64 = &v
			return nil
		case "fieldSfixed32", "field_sfixed32":
			if seen["FieldSfixed32"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["FieldSfixed32"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := jxpb.DecInt32(d)
			if err != nil {
				return err
			}
			m.FieldSfixed32 = &v
			return nil
		case "fieldSfixed64", "field_sfixed64":
			if seen["FieldSfixed64"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["FieldSfixed64"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := jxpb.DecInt64(d)
			if err != nil {
				return err
			}
			m.FieldSfixed64 = &v
			return nil
		case "fieldBool", "field_bool":
			if seen["FieldBool"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["FieldBool"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := d.Bool()
			if err != nil {
				return err
			}
			m.FieldBool = &v
			return nil
		case "fieldString", "field_string":
			if seen["FieldString"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["FieldString"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := d.Str()
			if err != nil {
				return err
			}
			m.FieldString = &v
			return nil
		case "fieldBytes", "field_bytes":
			if seen["FieldBytes"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["FieldBytes"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := jxpb.DecBytes(d)
			if err != nil {
				return err
			}
			m.FieldBytes = v
			return nil
		default:
			return fmt.Errorf("unknown field %q", key)
		}
	})
}

func (m *OptionalScalarTypes) MarshalJSON() ([]byte, error) {
	var e jx.Encoder
	m.Encode(&e)
	return e.Bytes(), nil
}

func (m *OptionalScalarTypes) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return m.Decode(d)
}

func (m *RepeatedScalarTypes) Encode(e *jx.Encoder) {
	if m == nil {
		e.ObjStart()
		e.ObjEnd()
		return
	}
	e.ObjStart()
	if len(m.FieldDouble) > 0 {
		e.FieldStart("fieldDouble")
		e.ArrStart()
		for _, v := range m.FieldDouble {
			jxpb.EncFloat64(e, v)
		}
		e.ArrEnd()
	}
	if len(m.FieldFloat) > 0 {
		e.FieldStart("fieldFloat")
		e.ArrStart()
		for _, v := range m.FieldFloat {
			jxpb.EncFloat32(e, v)
		}
		e.ArrEnd()
	}
	if len(m.FieldInt32) > 0 {
		e.FieldStart("fieldInt32")
		e.ArrStart()
		for _, v := range m.FieldInt32 {
			e.Int32(v)
		}
		e.ArrEnd()
	}
	if len(m.FieldInt64) > 0 {
		e.FieldStart("fieldInt64")
		e.ArrStart()
		for _, v := range m.FieldInt64 {
			jxpb.EncInt64(e, v)
		}
		e.ArrEnd()
	}
	if len(m.FieldUint32) > 0 {
		e.FieldStart("fieldUint32")
		e.ArrStart()
		for _, v := range m.FieldUint32 {
			e.UInt32(v)
		}
		e.ArrEnd()
	}
	if len(m.FieldUint64) > 0 {
		e.FieldStart("fieldUint64")
		e.ArrStart()
		for _, v := range m.FieldUint64 {
			jxpb.EncUint64(e, v)
		}
		e.ArrEnd()
	}
	if len(m.FieldSint32) > 0 {
		e.FieldStart("fieldSint32")
		e.ArrStart()
		for _, v := range m.FieldSint32 {
			e.Int32(v)
		}
		e.ArrEnd()
	}
	if len(m.FieldSint64) > 0 {
		e.FieldStart("fieldSint64")
		e.ArrStart()
		for _, v := range m.FieldSint64 {
			jxpb.EncInt64(e, v)
		}
		e.ArrEnd()
	}
	if len(m.FieldFixed32) > 0 {
		e.FieldStart("fieldFixed32")
		e.ArrStart()
		for _, v := range m.FieldFixed32 {
			e.UInt32(v)
		}
		e.ArrEnd()
	}
	if len(m.FieldFixed64) > 0 {
		e.FieldStart("fieldFixed64")
		e.ArrStart()
		for _, v := range m.FieldFixed64 {
			jxpb.EncUint64(e, v)
		}
		e.ArrEnd()
	}
	if len(m.FieldSfixed32) > 0 {
		e.FieldStart("fieldSfixed32")
		e.ArrStart()
		for _, v := range m.FieldSfixed32 {
			e.Int32(v)
		}
		e.ArrEnd()
	}
	if len(m.FieldSfixed64) > 0 {
		e.FieldStart("fieldSfixed64")
		e.ArrStart()
		for _, v := range m.FieldSfixed64 {
			jxpb.EncInt64(e, v)
		}
		e.ArrEnd()
	}
	if len(m.FieldBool) > 0 {
		e.FieldStart("fieldBool")
		e.ArrStart()
		for _, v := range m.FieldBool {
			e.Bool(v)
		}
		e.ArrEnd()
	}
	if len(m.FieldString) > 0 {
		e.FieldStart("fieldString")
		e.ArrStart()
		for _, v := range m.FieldString {
			e.Str(v)
		}
		e.ArrEnd()
	}
	if len(m.FieldBytes) > 0 {
		e.FieldStart("fieldBytes")
		e.ArrStart()
		for _, v := range m.FieldBytes {
			jxpb.EncBytes(e, v)
		}
		e.ArrEnd()
	}
	e.ObjEnd()
}

func (m *RepeatedScalarTypes) Decode(d *jx.Decoder) error {
	seen := map[string]bool{}
	return d.Obj(func(d *jx.Decoder, key string) error {
		switch key {
		case "fieldDouble", "field_double":
			if seen["FieldDouble"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["FieldDouble"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			return d.Arr(func(d *jx.Decoder) error {
				v, err := jxpb.DecFloat64(d)
				if err != nil {
					return err
				}
				m.FieldDouble = append(m.FieldDouble, v)
				return nil
			})
		case "fieldFloat", "field_float":
			if seen["FieldFloat"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["FieldFloat"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			return d.Arr(func(d *jx.Decoder) error {
				v, err := jxpb.DecFloat32(d)
				if err != nil {
					return err
				}
				m.FieldFloat = append(m.FieldFloat, v)
				return nil
			})
		case "fieldInt32", "field_int32":
			if seen["FieldInt32"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["FieldInt32"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			return d.Arr(func(d *jx.Decoder) error {
				v, err := jxpb.DecInt32(d)
				if err != nil {
					return err
				}
				m.FieldInt32 = append(m.FieldInt32, v)
				return nil
			})
		case "fieldInt64", "field_int64":
			if seen["FieldInt64"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["FieldInt64"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			return d.Arr(func(d *jx.Decoder) error {
				v, err := jxpb.DecInt64(d)
				if err != nil {
					return err
				}
				m.FieldInt64 = append(m.FieldInt64, v)
				return nil
			})
		case "fieldUint32", "field_uint32":
			if seen["FieldUint32"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["FieldUint32"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			return d.Arr(func(d *jx.Decoder) error {
				v, err := jxpb.DecUint32(d)
				if err != nil {
					return err
				}
				m.FieldUint32 = append(m.FieldUint32, v)
				return nil
			})
		case "fieldUint64", "field_uint64":
			if seen["FieldUint64"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["FieldUint64"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			return d.Arr(func(d *jx.Decoder) error {
				v, err := jxpb.DecUint64(d)
				if err != nil {
					return err
				}
				m.FieldUint64 = append(m.FieldUint64, v)
				return nil
			})
		case "fieldSint32", "field_sint32":
			if seen["FieldSint32"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["FieldSint32"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			return d.Arr(func(d *jx.Decoder) error {
				v, err := jxpb.DecInt32(d)
				if err != nil {
					return err
				}
				m.FieldSint32 = append(m.FieldSint32, v)
				return nil
			})
		case "fieldSint64", "field_sint64":
			if seen["FieldSint64"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["FieldSint64"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			return d.Arr(func(d *jx.Decoder) error {
				v, err := jxpb.DecInt64(d)
				if err != nil {
					return err
				}
				m.FieldSint64 = append(m.FieldSint64, v)
				return nil
			})
		case "fieldFixed32", "field_fixed32":
			if seen["FieldFixed32"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["FieldFixed32"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			return d.Arr(func(d *jx.Decoder) error {
				v, err := jxpb.DecUint32(d)
				if err != nil {
					return err
				}
				m.FieldFixed32 = append(m.FieldFixed32, v)
				return nil
			})
		case "fieldFixed64", "field_fixed64":
			if seen["FieldFixed64"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["FieldFixed64"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			return d.Arr(func(d *jx.Decoder) error {
				v, err := jxpb.DecUint64(d)
				if err != nil {
					return err
				}
				m.FieldFixed64 = append(m.FieldFixed64, v)
				return nil
			})
		case "fieldSfixed32", "field_sfixed32":
			if seen["FieldSfixed32"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["FieldSfixed32"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			return d.Arr(func(d *jx.Decoder) error {
				v, err := jxpb.DecInt32(d)
				if err != nil {
					return err
				}
				m.FieldSfixed32 = append(m.FieldSfixed32, v)
				return nil
			})
		case "fieldSfixed64", "field_sfixed64":
			if seen["FieldSfixed64"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["FieldSfixed64"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			return d.Arr(func(d *jx.Decoder) error {
				v, err := jxpb.DecInt64(d)
				if err != nil {
					return err
				}
				m.FieldSfixed64 = append(m.FieldSfixed64, v)
				return nil
			})
		case "fieldBool", "field_bool":
			if seen["FieldBool"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["FieldBool"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			return d.Arr(func(d *jx.Decoder) error {
				v, err := d.Bool()
				if err != nil {
					return err
				}
				m.FieldBool = append(m.FieldBool, v)
				return nil
			})
		case "fieldString", "field_string":
			if seen["FieldString"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["FieldString"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			return d.Arr(func(d *jx.Decoder) error {
				v, err := d.Str()
				if err != nil {
					return err
				}
				m.FieldString = append(m.FieldString, v)
				return nil
			})
		case "fieldBytes", "field_bytes":
			if seen["FieldBytes"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["FieldBytes"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			return d.Arr(func(d *jx.Decoder) error {
				v, err := jxpb.DecBytes(d)
				if err != nil {
					return err
				}
				m.FieldBytes = append(m.FieldBytes, v)
				return nil
			})
		default:
			return fmt.Errorf("unknown field %q", key)
		}
	})
}

func (m *RepeatedScalarTypes) MarshalJSON() ([]byte, error) {
	var e jx.Encoder
	m.Encode(&e)
	return e.Bytes(), nil
}

func (m *RepeatedScalarTypes) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return m.Decode(d)
}

func (m *Outer) Encode(e *jx.Encoder) {
	if m == nil {
		e.ObjStart()
		e.ObjEnd()
		return
	}
	e.ObjStart()
	if m.Inner != nil {
		e.FieldStart("inner")
		m.Inner.Encode(e)
	}
	if m.EnumField != 0 {
		e.FieldStart("enumField")
		if s, ok := Outer_NestedEnum_name[int32(m.EnumField)]; ok {
			e.Str(s)
		} else {
			e.Int32(int32(m.EnumField))
		}
	}
	if m.DeepInner != nil {
		e.FieldStart("deepInner")
		m.DeepInner.Encode(e)
	}
	e.ObjEnd()
}

func (m *Outer) Decode(d *jx.Decoder) error {
	seen := map[string]bool{}
	return d.Obj(func(d *jx.Decoder, key string) error {
		switch key {
		case "inner":
			if seen["Inner"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["Inner"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			m.Inner = &Outer_Inner{}
			return m.Inner.Decode(d)
		case "enumField", "enum_field":
			if seen["EnumField"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["EnumField"] = true
			switch d.Next() {
			case jx.String:
				s, err := d.Str()
				if err != nil {
					return err
				}
				n, ok := Outer_NestedEnum_value[s]
				if !ok {
					return fmt.Errorf("unknown enum value %q", s)
				}
				m.EnumField = Outer_NestedEnum(n)
				return nil
			case jx.Number:
				n, err := d.Int32()
				if err != nil {
					return err
				}
				m.EnumField = Outer_NestedEnum(n)
				return nil
			case jx.Null:
				return d.Null()
			default:
				return fmt.Errorf("invalid enum token %s", d.Next())
			}
		case "deepInner", "deep_inner":
			if seen["DeepInner"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["DeepInner"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			m.DeepInner = &Outer_Inner_DeepInner{}
			return m.DeepInner.Decode(d)
		default:
			return fmt.Errorf("unknown field %q", key)
		}
	})
}

func (m *Outer) MarshalJSON() ([]byte, error) {
	var e jx.Encoder
	m.Encode(&e)
	return e.Bytes(), nil
}

func (m *Outer) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return m.Decode(d)
}

func (m *Outer_Inner) Encode(e *jx.Encoder) {
	if m == nil {
		e.ObjStart()
		e.ObjEnd()
		return
	}
	e.ObjStart()
	if m.NestedEnum != 0 {
		e.FieldStart("nestedEnum")
		if s, ok := Outer_NestedEnum_name[int32(m.NestedEnum)]; ok {
			e.Str(s)
		} else {
			e.Int32(int32(m.NestedEnum))
		}
	}
	if m.Deep != nil {
		e.FieldStart("deep")
		m.Deep.Encode(e)
	}
	e.ObjEnd()
}

func (m *Outer_Inner) Decode(d *jx.Decoder) error {
	seen := map[string]bool{}
	return d.Obj(func(d *jx.Decoder, key string) error {
		switch key {
		case "nestedEnum", "nested_enum":
			if seen["NestedEnum"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["NestedEnum"] = true
			switch d.Next() {
			case jx.String:
				s, err := d.Str()
				if err != nil {
					return err
				}
				n, ok := Outer_NestedEnum_value[s]
				if !ok {
					return fmt.Errorf("unknown enum value %q", s)
				}
				m.NestedEnum = Outer_NestedEnum(n)
				return nil
			case jx.Number:
				n, err := d.Int32()
				if err != nil {
					return err
				}
				m.NestedEnum = Outer_NestedEnum(n)
				return nil
			case jx.Null:
				return d.Null()
			default:
				return fmt.Errorf("invalid enum token %s", d.Next())
			}
		case "deep":
			if seen["Deep"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["Deep"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			m.Deep = &Outer_Inner_DeepInner{}
			return m.Deep.Decode(d)
		default:
			return fmt.Errorf("unknown field %q", key)
		}
	})
}

func (m *Outer_Inner) MarshalJSON() ([]byte, error) {
	var e jx.Encoder
	m.Encode(&e)
	return e.Bytes(), nil
}

func (m *Outer_Inner) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return m.Decode(d)
}

func (m *Outer_Inner_DeepInner) Encode(e *jx.Encoder) {
	if m == nil {
		e.ObjStart()
		e.ObjEnd()
		return
	}
	e.ObjStart()
	if m.Value != "" {
		e.FieldStart("value")
		e.Str(m.Value)
	}
	e.ObjEnd()
}

func (m *Outer_Inner_DeepInner) Decode(d *jx.Decoder) error {
	seen := map[string]bool{}
	return d.Obj(func(d *jx.Decoder, key string) error {
		switch key {
		case "value":
			if seen["Value"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["Value"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := d.Str()
			if err != nil {
				return err
			}
			m.Value = v
			return nil
		default:
			return fmt.Errorf("unknown field %q", key)
		}
	})
}

func (m *Outer_Inner_DeepInner) MarshalJSON() ([]byte, error) {
	var e jx.Encoder
	m.Encode(&e)
	return e.Bytes(), nil
}

func (m *Outer_Inner_DeepInner) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return m.Decode(d)
}

func (m *EnumAndMessageFields) Encode(e *jx.Encoder) {
	if m == nil {
		e.ObjStart()
		e.ObjEnd()
		return
	}
	e.ObjStart()
	if m.SingularEnum != 0 {
		e.FieldStart("singularEnum")
		if s, ok := TopLevelEnum_name[int32(m.SingularEnum)]; ok {
			e.Str(s)
		} else {
			e.Int32(int32(m.SingularEnum))
		}
	}
	if m.OptionalEnum != nil {
		e.FieldStart("optionalEnum")
		if s, ok := TopLevelEnum_name[int32(*m.OptionalEnum)]; ok {
			e.Str(s)
		} else {
			e.Int32(int32(*m.OptionalEnum))
		}
	}
	if len(m.RepeatedEnum) > 0 {
		e.FieldStart("repeatedEnum")
		e.ArrStart()
		for _, v := range m.RepeatedEnum {
			if s, ok := TopLevelEnum_name[int32(v)]; ok {
				e.Str(s)
			} else {
				e.Int32(int32(v))
			}
		}
		e.ArrEnd()
	}
	if m.SingularMessage != nil {
		e.FieldStart("singularMessage")
		m.SingularMessage.Encode(e)
	}
	if m.OptionalMessage != nil {
		e.FieldStart("optionalMessage")
		m.OptionalMessage.Encode(e)
	}
	if len(m.RepeatedMessage) > 0 {
		e.FieldStart("repeatedMessage")
		e.ArrStart()
		for _, v := range m.RepeatedMessage {
			v.Encode(e)
		}
		e.ArrEnd()
	}
	if m.NestedEnum != 0 {
		e.FieldStart("nestedEnum")
		if s, ok := Outer_NestedEnum_name[int32(m.NestedEnum)]; ok {
			e.Str(s)
		} else {
			e.Int32(int32(m.NestedEnum))
		}
	}
	if m.NestedMessage != nil {
		e.FieldStart("nestedMessage")
		m.NestedMessage.Encode(e)
	}
	e.ObjEnd()
}

func (m *EnumAndMessageFields) Decode(d *jx.Decoder) error {
	seen := map[string]bool{}
	return d.Obj(func(d *jx.Decoder, key string) error {
		switch key {
		case "singularEnum", "singular_enum":
			if seen["SingularEnum"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["SingularEnum"] = true
			switch d.Next() {
			case jx.String:
				s, err := d.Str()
				if err != nil {
					return err
				}
				n, ok := TopLevelEnum_value[s]
				if !ok {
					return fmt.Errorf("unknown enum value %q", s)
				}
				m.SingularEnum = TopLevelEnum(n)
				return nil
			case jx.Number:
				n, err := d.Int32()
				if err != nil {
					return err
				}
				m.SingularEnum = TopLevelEnum(n)
				return nil
			case jx.Null:
				return d.Null()
			default:
				return fmt.Errorf("invalid enum token %s", d.Next())
			}
		case "optionalEnum", "optional_enum":
			if seen["OptionalEnum"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["OptionalEnum"] = true
			switch d.Next() {
			case jx.String:
				s, err := d.Str()
				if err != nil {
					return err
				}
				n, ok := TopLevelEnum_value[s]
				if !ok {
					return fmt.Errorf("unknown enum value %q", s)
				}
				v := TopLevelEnum(n)
				m.OptionalEnum = &v
				return nil
			case jx.Number:
				n, err := d.Int32()
				if err != nil {
					return err
				}
				v := TopLevelEnum(n)
				m.OptionalEnum = &v
				return nil
			case jx.Null:
				return d.Null()
			default:
				return fmt.Errorf("invalid enum token %s", d.Next())
			}
		case "repeatedEnum", "repeated_enum":
			if seen["RepeatedEnum"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["RepeatedEnum"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			return d.Arr(func(d *jx.Decoder) error {
				var n int32
				switch d.Next() {
				case jx.String:
					s, err := d.Str()
					if err != nil {
						return err
					}
					v, ok := TopLevelEnum_value[s]
					if !ok {
						return fmt.Errorf("unknown enum value %q", s)
					}
					n = v
				default:
					v, err := d.Int32()
					if err != nil {
						return err
					}
					n = v
				}
				m.RepeatedEnum = append(m.RepeatedEnum, TopLevelEnum(n))
				return nil
			})
		case "singularMessage", "singular_message":
			if seen["SingularMessage"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["SingularMessage"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			m.SingularMessage = &ScalarTypes{}
			return m.SingularMessage.Decode(d)
		case "optionalMessage", "optional_message":
			if seen["OptionalMessage"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["OptionalMessage"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			m.OptionalMessage = &ScalarTypes{}
			return m.OptionalMessage.Decode(d)
		case "repeatedMessage", "repeated_message":
			if seen["RepeatedMessage"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["RepeatedMessage"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			return d.Arr(func(d *jx.Decoder) error {
				el := &ScalarTypes{}
				if err := el.Decode(d); err != nil {
					return err
				}
				m.RepeatedMessage = append(m.RepeatedMessage, el)
				return nil
			})
		case "nestedEnum", "nested_enum":
			if seen["NestedEnum"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["NestedEnum"] = true
			switch d.Next() {
			case jx.String:
				s, err := d.Str()
				if err != nil {
					return err
				}
				n, ok := Outer_NestedEnum_value[s]
				if !ok {
					return fmt.Errorf("unknown enum value %q", s)
				}
				m.NestedEnum = Outer_NestedEnum(n)
				return nil
			case jx.Number:
				n, err := d.Int32()
				if err != nil {
					return err
				}
				m.NestedEnum = Outer_NestedEnum(n)
				return nil
			case jx.Null:
				return d.Null()
			default:
				return fmt.Errorf("invalid enum token %s", d.Next())
			}
		case "nestedMessage", "nested_message":
			if seen["NestedMessage"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["NestedMessage"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			m.NestedMessage = &Outer_Inner{}
			return m.NestedMessage.Decode(d)
		default:
			return fmt.Errorf("unknown field %q", key)
		}
	})
}

func (m *EnumAndMessageFields) MarshalJSON() ([]byte, error) {
	var e jx.Encoder
	m.Encode(&e)
	return e.Bytes(), nil
}

func (m *EnumAndMessageFields) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return m.Decode(d)
}

func (m *MapKeyTypes) Encode(e *jx.Encoder) {
	if m == nil {
		e.ObjStart()
		e.ObjEnd()
		return
	}
	e.ObjStart()
	if len(m.Int32Key) > 0 {
		e.FieldStart("int32Key")
		e.ObjStart()
		for k, v := range m.Int32Key {
			e.FieldStart(strconv.FormatInt(int64(k), 10))
			e.Str(v)
		}
		e.ObjEnd()
	}
	if len(m.Int64Key) > 0 {
		e.FieldStart("int64Key")
		e.ObjStart()
		for k, v := range m.Int64Key {
			e.FieldStart(strconv.FormatInt(k, 10))
			e.Str(v)
		}
		e.ObjEnd()
	}
	if len(m.Uint32Key) > 0 {
		e.FieldStart("uint32Key")
		e.ObjStart()
		for k, v := range m.Uint32Key {
			e.FieldStart(strconv.FormatInt(int64(k), 10))
			e.Str(v)
		}
		e.ObjEnd()
	}
	if len(m.Uint64Key) > 0 {
		e.FieldStart("uint64Key")
		e.ObjStart()
		for k, v := range m.Uint64Key {
			e.FieldStart(strconv.FormatUint(k, 10))
			e.Str(v)
		}
		e.ObjEnd()
	}
	if len(m.Sint32Key) > 0 {
		e.FieldStart("sint32Key")
		e.ObjStart()
		for k, v := range m.Sint32Key {
			e.FieldStart(strconv.FormatInt(int64(k), 10))
			e.Str(v)
		}
		e.ObjEnd()
	}
	if len(m.Sint64Key) > 0 {
		e.FieldStart("sint64Key")
		e.ObjStart()
		for k, v := range m.Sint64Key {
			e.FieldStart(strconv.FormatInt(k, 10))
			e.Str(v)
		}
		e.ObjEnd()
	}
	if len(m.Fixed32Key) > 0 {
		e.FieldStart("fixed32Key")
		e.ObjStart()
		for k, v := range m.Fixed32Key {
			e.FieldStart(strconv.FormatInt(int64(k), 10))
			e.Str(v)
		}
		e.ObjEnd()
	}
	if len(m.Fixed64Key) > 0 {
		e.FieldStart("fixed64Key")
		e.ObjStart()
		for k, v := range m.Fixed64Key {
			e.FieldStart(strconv.FormatUint(k, 10))
			e.Str(v)
		}
		e.ObjEnd()
	}
	if len(m.Sfixed32Key) > 0 {
		e.FieldStart("sfixed32Key")
		e.ObjStart()
		for k, v := range m.Sfixed32Key {
			e.FieldStart(strconv.FormatInt(int64(k), 10))
			e.Str(v)
		}
		e.ObjEnd()
	}
	if len(m.Sfixed64Key) > 0 {
		e.FieldStart("sfixed64Key")
		e.ObjStart()
		for k, v := range m.Sfixed64Key {
			e.FieldStart(strconv.FormatInt(k, 10))
			e.Str(v)
		}
		e.ObjEnd()
	}
	if len(m.BoolKey) > 0 {
		e.FieldStart("boolKey")
		e.ObjStart()
		for k, v := range m.BoolKey {
			e.FieldStart(strconv.FormatBool(k))
			e.Str(v)
		}
		e.ObjEnd()
	}
	if len(m.StringKey) > 0 {
		e.FieldStart("stringKey")
		e.ObjStart()
		for k, v := range m.StringKey {
			e.FieldStart(k)
			e.Str(v)
		}
		e.ObjEnd()
	}
	e.ObjEnd()
}

func (m *MapKeyTypes) Decode(d *jx.Decoder) error {
	seen := map[string]bool{}
	return d.Obj(func(d *jx.Decoder, key string) error {
		switch key {
		case "int32Key", "int32_key":
			if seen["Int32Key"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["Int32Key"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			if m.Int32Key == nil {
				m.Int32Key = make(map[int32]string)
			}
			return d.Obj(func(d *jx.Decoder, ks string) error {
				mk64, err := strconv.ParseInt(ks, 10, 32)
				if err != nil {
					return err
				}
				mk := int32(mk64)
				var mv string
				tv, err := d.Str()
				if err != nil {
					return err
				}
				mv = tv
				m.Int32Key[mk] = mv
				return nil
			})
		case "int64Key", "int64_key":
			if seen["Int64Key"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["Int64Key"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			if m.Int64Key == nil {
				m.Int64Key = make(map[int64]string)
			}
			return d.Obj(func(d *jx.Decoder, ks string) error {
				mk, err := strconv.ParseInt(ks, 10, 64)
				if err != nil {
					return err
				}
				var mv string
				tv, err := d.Str()
				if err != nil {
					return err
				}
				mv = tv
				m.Int64Key[mk] = mv
				return nil
			})
		case "uint32Key", "uint32_key":
			if seen["Uint32Key"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["Uint32Key"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			if m.Uint32Key == nil {
				m.Uint32Key = make(map[uint32]string)
			}
			return d.Obj(func(d *jx.Decoder, ks string) error {
				mk64, err := strconv.ParseUint(ks, 10, 32)
				if err != nil {
					return err
				}
				mk := uint32(mk64)
				var mv string
				tv, err := d.Str()
				if err != nil {
					return err
				}
				mv = tv
				m.Uint32Key[mk] = mv
				return nil
			})
		case "uint64Key", "uint64_key":
			if seen["Uint64Key"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["Uint64Key"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			if m.Uint64Key == nil {
				m.Uint64Key = make(map[uint64]string)
			}
			return d.Obj(func(d *jx.Decoder, ks string) error {
				mk, err := strconv.ParseUint(ks, 10, 64)
				if err != nil {
					return err
				}
				var mv string
				tv, err := d.Str()
				if err != nil {
					return err
				}
				mv = tv
				m.Uint64Key[mk] = mv
				return nil
			})
		case "sint32Key", "sint32_key":
			if seen["Sint32Key"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["Sint32Key"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			if m.Sint32Key == nil {
				m.Sint32Key = make(map[int32]string)
			}
			return d.Obj(func(d *jx.Decoder, ks string) error {
				mk64, err := strconv.ParseInt(ks, 10, 32)
				if err != nil {
					return err
				}
				mk := int32(mk64)
				var mv string
				tv, err := d.Str()
				if err != nil {
					return err
				}
				mv = tv
				m.Sint32Key[mk] = mv
				return nil
			})
		case "sint64Key", "sint64_key":
			if seen["Sint64Key"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["Sint64Key"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			if m.Sint64Key == nil {
				m.Sint64Key = make(map[int64]string)
			}
			return d.Obj(func(d *jx.Decoder, ks string) error {
				mk, err := strconv.ParseInt(ks, 10, 64)
				if err != nil {
					return err
				}
				var mv string
				tv, err := d.Str()
				if err != nil {
					return err
				}
				mv = tv
				m.Sint64Key[mk] = mv
				return nil
			})
		case "fixed32Key", "fixed32_key":
			if seen["Fixed32Key"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["Fixed32Key"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			if m.Fixed32Key == nil {
				m.Fixed32Key = make(map[uint32]string)
			}
			return d.Obj(func(d *jx.Decoder, ks string) error {
				mk64, err := strconv.ParseUint(ks, 10, 32)
				if err != nil {
					return err
				}
				mk := uint32(mk64)
				var mv string
				tv, err := d.Str()
				if err != nil {
					return err
				}
				mv = tv
				m.Fixed32Key[mk] = mv
				return nil
			})
		case "fixed64Key", "fixed64_key":
			if seen["Fixed64Key"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["Fixed64Key"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			if m.Fixed64Key == nil {
				m.Fixed64Key = make(map[uint64]string)
			}
			return d.Obj(func(d *jx.Decoder, ks string) error {
				mk, err := strconv.ParseUint(ks, 10, 64)
				if err != nil {
					return err
				}
				var mv string
				tv, err := d.Str()
				if err != nil {
					return err
				}
				mv = tv
				m.Fixed64Key[mk] = mv
				return nil
			})
		case "sfixed32Key", "sfixed32_key":
			if seen["Sfixed32Key"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["Sfixed32Key"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			if m.Sfixed32Key == nil {
				m.Sfixed32Key = make(map[int32]string)
			}
			return d.Obj(func(d *jx.Decoder, ks string) error {
				mk64, err := strconv.ParseInt(ks, 10, 32)
				if err != nil {
					return err
				}
				mk := int32(mk64)
				var mv string
				tv, err := d.Str()
				if err != nil {
					return err
				}
				mv = tv
				m.Sfixed32Key[mk] = mv
				return nil
			})
		case "sfixed64Key", "sfixed64_key":
			if seen["Sfixed64Key"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["Sfixed64Key"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			if m.Sfixed64Key == nil {
				m.Sfixed64Key = make(map[int64]string)
			}
			return d.Obj(func(d *jx.Decoder, ks string) error {
				mk, err := strconv.ParseInt(ks, 10, 64)
				if err != nil {
					return err
				}
				var mv string
				tv, err := d.Str()
				if err != nil {
					return err
				}
				mv = tv
				m.Sfixed64Key[mk] = mv
				return nil
			})
		case "boolKey", "bool_key":
			if seen["BoolKey"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["BoolKey"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			if m.BoolKey == nil {
				m.BoolKey = make(map[bool]string)
			}
			return d.Obj(func(d *jx.Decoder, ks string) error {
				mk, err := strconv.ParseBool(ks)
				if err != nil {
					return err
				}
				var mv string
				tv, err := d.Str()
				if err != nil {
					return err
				}
				mv = tv
				m.BoolKey[mk] = mv
				return nil
			})
		case "stringKey", "string_key":
			if seen["StringKey"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["StringKey"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			if m.StringKey == nil {
				m.StringKey = make(map[string]string)
			}
			return d.Obj(func(d *jx.Decoder, ks string) error {
				mk := ks
				var mv string
				tv, err := d.Str()
				if err != nil {
					return err
				}
				mv = tv
				m.StringKey[mk] = mv
				return nil
			})
		default:
			return fmt.Errorf("unknown field %q", key)
		}
	})
}

func (m *MapKeyTypes) MarshalJSON() ([]byte, error) {
	var e jx.Encoder
	m.Encode(&e)
	return e.Bytes(), nil
}

func (m *MapKeyTypes) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return m.Decode(d)
}

func (m *MapValueTypes) Encode(e *jx.Encoder) {
	if m == nil {
		e.ObjStart()
		e.ObjEnd()
		return
	}
	e.ObjStart()
	if len(m.DoubleValue) > 0 {
		e.FieldStart("doubleValue")
		e.ObjStart()
		for k, v := range m.DoubleValue {
			e.FieldStart(k)
			jxpb.EncFloat64(e, v)
		}
		e.ObjEnd()
	}
	if len(m.FloatValue) > 0 {
		e.FieldStart("floatValue")
		e.ObjStart()
		for k, v := range m.FloatValue {
			e.FieldStart(k)
			jxpb.EncFloat32(e, v)
		}
		e.ObjEnd()
	}
	if len(m.Int32Value) > 0 {
		e.FieldStart("int32Value")
		e.ObjStart()
		for k, v := range m.Int32Value {
			e.FieldStart(k)
			e.Int32(v)
		}
		e.ObjEnd()
	}
	if len(m.Int64Value) > 0 {
		e.FieldStart("int64Value")
		e.ObjStart()
		for k, v := range m.Int64Value {
			e.FieldStart(k)
			jxpb.EncInt64(e, v)
		}
		e.ObjEnd()
	}
	if len(m.Uint32Value) > 0 {
		e.FieldStart("uint32Value")
		e.ObjStart()
		for k, v := range m.Uint32Value {
			e.FieldStart(k)
			e.UInt32(v)
		}
		e.ObjEnd()
	}
	if len(m.Uint64Value) > 0 {
		e.FieldStart("uint64Value")
		e.ObjStart()
		for k, v := range m.Uint64Value {
			e.FieldStart(k)
			jxpb.EncUint64(e, v)
		}
		e.ObjEnd()
	}
	if len(m.BoolValue) > 0 {
		e.FieldStart("boolValue")
		e.ObjStart()
		for k, v := range m.BoolValue {
			e.FieldStart(k)
			e.Bool(v)
		}
		e.ObjEnd()
	}
	if len(m.StringValue) > 0 {
		e.FieldStart("stringValue")
		e.ObjStart()
		for k, v := range m.StringValue {
			e.FieldStart(k)
			e.Str(v)
		}
		e.ObjEnd()
	}
	if len(m.BytesValue) > 0 {
		e.FieldStart("bytesValue")
		e.ObjStart()
		for k, v := range m.BytesValue {
			e.FieldStart(k)
			jxpb.EncBytes(e, v)
		}
		e.ObjEnd()
	}
	if len(m.EnumValue) > 0 {
		e.FieldStart("enumValue")
		e.ObjStart()
		for k, v := range m.EnumValue {
			e.FieldStart(k)
			if s, ok := TopLevelEnum_name[int32(v)]; ok {
				e.Str(s)
			} else {
				e.Int32(int32(v))
			}
		}
		e.ObjEnd()
	}
	if len(m.MessageValue) > 0 {
		e.FieldStart("messageValue")
		e.ObjStart()
		for k, v := range m.MessageValue {
			e.FieldStart(k)
			v.Encode(e)
		}
		e.ObjEnd()
	}
	e.ObjEnd()
}

func (m *MapValueTypes) Decode(d *jx.Decoder) error {
	seen := map[string]bool{}
	return d.Obj(func(d *jx.Decoder, key string) error {
		switch key {
		case "doubleValue", "double_value":
			if seen["DoubleValue"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["DoubleValue"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			if m.DoubleValue == nil {
				m.DoubleValue = make(map[string]float64)
			}
			return d.Obj(func(d *jx.Decoder, ks string) error {
				mk := ks
				var mv float64
				tv, err := jxpb.DecFloat64(d)
				if err != nil {
					return err
				}
				mv = tv
				m.DoubleValue[mk] = mv
				return nil
			})
		case "floatValue", "float_value":
			if seen["FloatValue"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["FloatValue"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			if m.FloatValue == nil {
				m.FloatValue = make(map[string]float32)
			}
			return d.Obj(func(d *jx.Decoder, ks string) error {
				mk := ks
				var mv float32
				tv, err := jxpb.DecFloat32(d)
				if err != nil {
					return err
				}
				mv = tv
				m.FloatValue[mk] = mv
				return nil
			})
		case "int32Value", "int32_value":
			if seen["Int32Value"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["Int32Value"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			if m.Int32Value == nil {
				m.Int32Value = make(map[string]int32)
			}
			return d.Obj(func(d *jx.Decoder, ks string) error {
				mk := ks
				var mv int32
				tv, err := jxpb.DecInt32(d)
				if err != nil {
					return err
				}
				mv = tv
				m.Int32Value[mk] = mv
				return nil
			})
		case "int64Value", "int64_value":
			if seen["Int64Value"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["Int64Value"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			if m.Int64Value == nil {
				m.Int64Value = make(map[string]int64)
			}
			return d.Obj(func(d *jx.Decoder, ks string) error {
				mk := ks
				var mv int64
				tv, err := jxpb.DecInt64(d)
				if err != nil {
					return err
				}
				mv = tv
				m.Int64Value[mk] = mv
				return nil
			})
		case "uint32Value", "uint32_value":
			if seen["Uint32Value"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["Uint32Value"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			if m.Uint32Value == nil {
				m.Uint32Value = make(map[string]uint32)
			}
			return d.Obj(func(d *jx.Decoder, ks string) error {
				mk := ks
				var mv uint32
				tv, err := jxpb.DecUint32(d)
				if err != nil {
					return err
				}
				mv = tv
				m.Uint32Value[mk] = mv
				return nil
			})
		case "uint64Value", "uint64_value":
			if seen["Uint64Value"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["Uint64Value"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			if m.Uint64Value == nil {
				m.Uint64Value = make(map[string]uint64)
			}
			return d.Obj(func(d *jx.Decoder, ks string) error {
				mk := ks
				var mv uint64
				tv, err := jxpb.DecUint64(d)
				if err != nil {
					return err
				}
				mv = tv
				m.Uint64Value[mk] = mv
				return nil
			})
		case "boolValue", "bool_value":
			if seen["BoolValue"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["BoolValue"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			if m.BoolValue == nil {
				m.BoolValue = make(map[string]bool)
			}
			return d.Obj(func(d *jx.Decoder, ks string) error {
				mk := ks
				var mv bool
				tv, err := d.Bool()
				if err != nil {
					return err
				}
				mv = tv
				m.BoolValue[mk] = mv
				return nil
			})
		case "stringValue", "string_value":
			if seen["StringValue"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["StringValue"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			if m.StringValue == nil {
				m.StringValue = make(map[string]string)
			}
			return d.Obj(func(d *jx.Decoder, ks string) error {
				mk := ks
				var mv string
				tv, err := d.Str()
				if err != nil {
					return err
				}
				mv = tv
				m.StringValue[mk] = mv
				return nil
			})
		case "bytesValue", "bytes_value":
			if seen["BytesValue"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["BytesValue"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			if m.BytesValue == nil {
				m.BytesValue = make(map[string][]byte)
			}
			return d.Obj(func(d *jx.Decoder, ks string) error {
				mk := ks
				var mv []byte
				tv, err := jxpb.DecBytes(d)
				if err != nil {
					return err
				}
				mv = tv
				m.BytesValue[mk] = mv
				return nil
			})
		case "enumValue", "enum_value":
			if seen["EnumValue"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["EnumValue"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			if m.EnumValue == nil {
				m.EnumValue = make(map[string]TopLevelEnum)
			}
			return d.Obj(func(d *jx.Decoder, ks string) error {
				mk := ks
				var mv TopLevelEnum
				switch d.Next() {
				case jx.String:
					s, err := d.Str()
					if err != nil {
						return err
					}
					n, ok := TopLevelEnum_value[s]
					if !ok {
						return fmt.Errorf("unknown enum value %q", s)
					}
					mv = TopLevelEnum(n)
				default:
					n, err := d.Int32()
					if err != nil {
						return err
					}
					mv = TopLevelEnum(n)
				}
				m.EnumValue[mk] = mv
				return nil
			})
		case "messageValue", "message_value":
			if seen["MessageValue"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["MessageValue"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			if m.MessageValue == nil {
				m.MessageValue = make(map[string]*ScalarTypes)
			}
			return d.Obj(func(d *jx.Decoder, ks string) error {
				mk := ks
				var mv *ScalarTypes
				mv = &ScalarTypes{}
				if err := mv.Decode(d); err != nil {
					return err
				}
				m.MessageValue[mk] = mv
				return nil
			})
		default:
			return fmt.Errorf("unknown field %q", key)
		}
	})
}

func (m *MapValueTypes) MarshalJSON() ([]byte, error) {
	var e jx.Encoder
	m.Encode(&e)
	return e.Bytes(), nil
}

func (m *MapValueTypes) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return m.Decode(d)
}

func (m *OneofContainer) Encode(e *jx.Encoder) {
	if m == nil {
		e.ObjStart()
		e.ObjEnd()
		return
	}
	e.ObjStart()
	if m.OutsideOneof != "" {
		e.FieldStart("outsideOneof")
		e.Str(m.OutsideOneof)
	}
	switch v := m.Choice.(type) {
	case *OneofContainer_ChoiceDouble:
		e.FieldStart("choiceDouble")
		jxpb.EncFloat64(e, v.ChoiceDouble)
	case *OneofContainer_ChoiceInt32:
		e.FieldStart("choiceInt32")
		e.Int32(v.ChoiceInt32)
	case *OneofContainer_ChoiceBool:
		e.FieldStart("choiceBool")
		e.Bool(v.ChoiceBool)
	case *OneofContainer_ChoiceString:
		e.FieldStart("choiceString")
		e.Str(v.ChoiceString)
	case *OneofContainer_ChoiceBytes:
		e.FieldStart("choiceBytes")
		jxpb.EncBytes(e, v.ChoiceBytes)
	case *OneofContainer_ChoiceEnum:
		e.FieldStart("choiceEnum")
		if s, ok := TopLevelEnum_name[int32(v.ChoiceEnum)]; ok {
			e.Str(s)
		} else {
			e.Int32(int32(v.ChoiceEnum))
		}
	case *OneofContainer_ChoiceMessage:
		e.FieldStart("choiceMessage")
		v.ChoiceMessage.Encode(e)
	}
	switch v := m.Other.(type) {
	case *OneofContainer_OtherA:
		e.FieldStart("otherA")
		e.Str(v.OtherA)
	case *OneofContainer_OtherB:
		e.FieldStart("otherB")
		jxpb.EncInt64(e, v.OtherB)
	}
	e.ObjEnd()
}

func (m *OneofContainer) Decode(d *jx.Decoder) error {
	seen := map[string]bool{}
	return d.Obj(func(d *jx.Decoder, key string) error {
		switch key {
		case "outsideOneof", "outside_oneof":
			if seen["OutsideOneof"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["OutsideOneof"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := d.Str()
			if err != nil {
				return err
			}
			m.OutsideOneof = v
			return nil
		case "choiceDouble", "choice_double":
			if seen["oneof:Choice"] {
				return fmt.Errorf("multiple keys for oneof choice")
			}
			seen["oneof:Choice"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			val, err := jxpb.DecFloat64(d)
			if err != nil {
				return err
			}
			m.Choice = &OneofContainer_ChoiceDouble{ChoiceDouble: val}
			return nil
		case "choiceInt32", "choice_int32":
			if seen["oneof:Choice"] {
				return fmt.Errorf("multiple keys for oneof choice")
			}
			seen["oneof:Choice"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			val, err := jxpb.DecInt32(d)
			if err != nil {
				return err
			}
			m.Choice = &OneofContainer_ChoiceInt32{ChoiceInt32: val}
			return nil
		case "choiceBool", "choice_bool":
			if seen["oneof:Choice"] {
				return fmt.Errorf("multiple keys for oneof choice")
			}
			seen["oneof:Choice"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			val, err := d.Bool()
			if err != nil {
				return err
			}
			m.Choice = &OneofContainer_ChoiceBool{ChoiceBool: val}
			return nil
		case "choiceString", "choice_string":
			if seen["oneof:Choice"] {
				return fmt.Errorf("multiple keys for oneof choice")
			}
			seen["oneof:Choice"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			val, err := d.Str()
			if err != nil {
				return err
			}
			m.Choice = &OneofContainer_ChoiceString{ChoiceString: val}
			return nil
		case "choiceBytes", "choice_bytes":
			if seen["oneof:Choice"] {
				return fmt.Errorf("multiple keys for oneof choice")
			}
			seen["oneof:Choice"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			val, err := jxpb.DecBytes(d)
			if err != nil {
				return err
			}
			m.Choice = &OneofContainer_ChoiceBytes{ChoiceBytes: val}
			return nil
		case "choiceEnum", "choice_enum":
			if seen["oneof:Choice"] {
				return fmt.Errorf("multiple keys for oneof choice")
			}
			seen["oneof:Choice"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			w := &OneofContainer_ChoiceEnum{}
			switch d.Next() {
			case jx.String:
				s, err := d.Str()
				if err != nil {
					return err
				}
				n, ok := TopLevelEnum_value[s]
				if !ok {
					return fmt.Errorf("unknown enum value %q", s)
				}
				w.ChoiceEnum = TopLevelEnum(n)
			default:
				n, err := d.Int32()
				if err != nil {
					return err
				}
				w.ChoiceEnum = TopLevelEnum(n)
			}
			m.Choice = w
			return nil
		case "choiceMessage", "choice_message":
			if seen["oneof:Choice"] {
				return fmt.Errorf("multiple keys for oneof choice")
			}
			seen["oneof:Choice"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			w := &OneofContainer_ChoiceMessage{}
			w.ChoiceMessage = &ScalarTypes{}
			if err := w.ChoiceMessage.Decode(d); err != nil {
				return err
			}
			m.Choice = w
			return nil
		case "otherA", "other_a":
			if seen["oneof:Other"] {
				return fmt.Errorf("multiple keys for oneof other")
			}
			seen["oneof:Other"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			val, err := d.Str()
			if err != nil {
				return err
			}
			m.Other = &OneofContainer_OtherA{OtherA: val}
			return nil
		case "otherB", "other_b":
			if seen["oneof:Other"] {
				return fmt.Errorf("multiple keys for oneof other")
			}
			seen["oneof:Other"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			val, err := jxpb.DecInt64(d)
			if err != nil {
				return err
			}
			m.Other = &OneofContainer_OtherB{OtherB: val}
			return nil
		default:
			return fmt.Errorf("unknown field %q", key)
		}
	})
}

func (m *OneofContainer) MarshalJSON() ([]byte, error) {
	var e jx.Encoder
	m.Encode(&e)
	return e.Bytes(), nil
}

func (m *OneofContainer) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return m.Decode(d)
}

func (m *WellKnownTypes) Encode(e *jx.Encoder) {
	if m == nil {
		e.ObjStart()
		e.ObjEnd()
		return
	}
	e.ObjStart()
	if m.Timestamp != nil {
		e.FieldStart("timestamp")
		jxpb.EncTimestamp(e, m.Timestamp)
	}
	if m.Duration != nil {
		e.FieldStart("duration")
		jxpb.EncDuration(e, m.Duration)
	}
	if m.Any != nil {
		e.FieldStart("any")
		jxpb.EncAny(e, m.Any)
	}
	if m.Empty != nil {
		e.FieldStart("empty")
		jxpb.EncEmpty(e, m.Empty)
	}
	if m.FieldMask != nil {
		e.FieldStart("fieldMask")
		jxpb.EncFieldMask(e, m.FieldMask)
	}
	if m.Struct != nil {
		e.FieldStart("struct")
		jxpb.EncStruct(e, m.Struct)
	}
	if m.Value != nil {
		e.FieldStart("value")
		jxpb.EncValue(e, m.Value)
	}
	if m.ListValue != nil {
		e.FieldStart("listValue")
		jxpb.EncListValue(e, m.ListValue)
	}
	if m.DoubleWrapper != nil {
		e.FieldStart("doubleWrapper")
		jxpb.EncDoubleValue(e, m.DoubleWrapper)
	}
	if m.FloatWrapper != nil {
		e.FieldStart("floatWrapper")
		jxpb.EncFloatValue(e, m.FloatWrapper)
	}
	if m.Int32Wrapper != nil {
		e.FieldStart("int32Wrapper")
		jxpb.EncInt32Value(e, m.Int32Wrapper)
	}
	if m.Int64Wrapper != nil {
		e.FieldStart("int64Wrapper")
		jxpb.EncInt64Value(e, m.Int64Wrapper)
	}
	if m.Uint32Wrapper != nil {
		e.FieldStart("uint32Wrapper")
		jxpb.EncUint32Value(e, m.Uint32Wrapper)
	}
	if m.Uint64Wrapper != nil {
		e.FieldStart("uint64Wrapper")
		jxpb.EncUint64Value(e, m.Uint64Wrapper)
	}
	if m.BoolWrapper != nil {
		e.FieldStart("boolWrapper")
		jxpb.EncBoolValue(e, m.BoolWrapper)
	}
	if m.StringWrapper != nil {
		e.FieldStart("stringWrapper")
		jxpb.EncStringValue(e, m.StringWrapper)
	}
	if m.BytesWrapper != nil {
		e.FieldStart("bytesWrapper")
		jxpb.EncBytesValue(e, m.BytesWrapper)
	}
	if len(m.RepeatedTimestamp) > 0 {
		e.FieldStart("repeatedTimestamp")
		e.ArrStart()
		for _, v := range m.RepeatedTimestamp {
			jxpb.EncTimestamp(e, v)
		}
		e.ArrEnd()
	}
	if len(m.MapDuration) > 0 {
		e.FieldStart("mapDuration")
		e.ObjStart()
		for k, v := range m.MapDuration {
			e.FieldStart(k)
			jxpb.EncDuration(e, v)
		}
		e.ObjEnd()
	}
	e.ObjEnd()
}

func (m *WellKnownTypes) Decode(d *jx.Decoder) error {
	seen := map[string]bool{}
	return d.Obj(func(d *jx.Decoder, key string) error {
		switch key {
		case "timestamp":
			if seen["Timestamp"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["Timestamp"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			m.Timestamp = &timestamppb.Timestamp{}
			return jxpb.DecTimestamp(d, m.Timestamp)
		case "duration":
			if seen["Duration"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["Duration"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			m.Duration = &durationpb.Duration{}
			return jxpb.DecDuration(d, m.Duration)
		case "any":
			if seen["Any"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["Any"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			m.Any = &anypb.Any{}
			return jxpb.DecAny(d, m.Any)
		case "empty":
			if seen["Empty"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["Empty"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			m.Empty = &emptypb.Empty{}
			return jxpb.DecEmpty(d, m.Empty)
		case "fieldMask", "field_mask":
			if seen["FieldMask"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["FieldMask"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			m.FieldMask = &fieldmaskpb.FieldMask{}
			return jxpb.DecFieldMask(d, m.FieldMask)
		case "struct":
			if seen["Struct"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["Struct"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			m.Struct = &structpb.Struct{}
			return jxpb.DecStruct(d, m.Struct)
		case "value":
			if seen["Value"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["Value"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			m.Value = &structpb.Value{}
			return jxpb.DecValue(d, m.Value)
		case "listValue", "list_value":
			if seen["ListValue"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["ListValue"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			m.ListValue = &structpb.ListValue{}
			return jxpb.DecListValue(d, m.ListValue)
		case "doubleWrapper", "double_wrapper":
			if seen["DoubleWrapper"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["DoubleWrapper"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			m.DoubleWrapper = &wrapperspb.DoubleValue{}
			return jxpb.DecDoubleValue(d, m.DoubleWrapper)
		case "floatWrapper", "float_wrapper":
			if seen["FloatWrapper"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["FloatWrapper"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			m.FloatWrapper = &wrapperspb.FloatValue{}
			return jxpb.DecFloatValue(d, m.FloatWrapper)
		case "int32Wrapper", "int32_wrapper":
			if seen["Int32Wrapper"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["Int32Wrapper"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			m.Int32Wrapper = &wrapperspb.Int32Value{}
			return jxpb.DecInt32Value(d, m.Int32Wrapper)
		case "int64Wrapper", "int64_wrapper":
			if seen["Int64Wrapper"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["Int64Wrapper"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			m.Int64Wrapper = &wrapperspb.Int64Value{}
			return jxpb.DecInt64Value(d, m.Int64Wrapper)
		case "uint32Wrapper", "uint32_wrapper":
			if seen["Uint32Wrapper"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["Uint32Wrapper"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			m.Uint32Wrapper = &wrapperspb.UInt32Value{}
			return jxpb.DecUint32Value(d, m.Uint32Wrapper)
		case "uint64Wrapper", "uint64_wrapper":
			if seen["Uint64Wrapper"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["Uint64Wrapper"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			m.Uint64Wrapper = &wrapperspb.UInt64Value{}
			return jxpb.DecUint64Value(d, m.Uint64Wrapper)
		case "boolWrapper", "bool_wrapper":
			if seen["BoolWrapper"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["BoolWrapper"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			m.BoolWrapper = &wrapperspb.BoolValue{}
			return jxpb.DecBoolValue(d, m.BoolWrapper)
		case "stringWrapper", "string_wrapper":
			if seen["StringWrapper"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["StringWrapper"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			m.StringWrapper = &wrapperspb.StringValue{}
			return jxpb.DecStringValue(d, m.StringWrapper)
		case "bytesWrapper", "bytes_wrapper":
			if seen["BytesWrapper"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["BytesWrapper"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			m.BytesWrapper = &wrapperspb.BytesValue{}
			return jxpb.DecBytesValue(d, m.BytesWrapper)
		case "repeatedTimestamp", "repeated_timestamp":
			if seen["RepeatedTimestamp"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["RepeatedTimestamp"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			return d.Arr(func(d *jx.Decoder) error {
				el := &timestamppb.Timestamp{}
				if err := jxpb.DecTimestamp(d, el); err != nil {
					return err
				}
				m.RepeatedTimestamp = append(m.RepeatedTimestamp, el)
				return nil
			})
		case "mapDuration", "map_duration":
			if seen["MapDuration"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["MapDuration"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			if m.MapDuration == nil {
				m.MapDuration = make(map[string]*durationpb.Duration)
			}
			return d.Obj(func(d *jx.Decoder, ks string) error {
				mk := ks
				var mv *durationpb.Duration
				mv = &durationpb.Duration{}
				if err := jxpb.DecDuration(d, mv); err != nil {
					return err
				}
				m.MapDuration[mk] = mv
				return nil
			})
		default:
			return fmt.Errorf("unknown field %q", key)
		}
	})
}

func (m *WellKnownTypes) MarshalJSON() ([]byte, error) {
	var e jx.Encoder
	m.Encode(&e)
	return e.Bytes(), nil
}

func (m *WellKnownTypes) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return m.Decode(d)
}

func (m *TreeNode) Encode(e *jx.Encoder) {
	if m == nil {
		e.ObjStart()
		e.ObjEnd()
		return
	}
	e.ObjStart()
	if m.Id != "" {
		e.FieldStart("id")
		e.Str(m.Id)
	}
	if m.Parent != nil {
		e.FieldStart("parent")
		m.Parent.Encode(e)
	}
	if len(m.Children) > 0 {
		e.FieldStart("children")
		e.ArrStart()
		for _, v := range m.Children {
			v.Encode(e)
		}
		e.ArrEnd()
	}
	if len(m.Named) > 0 {
		e.FieldStart("named")
		e.ObjStart()
		for k, v := range m.Named {
			e.FieldStart(k)
			v.Encode(e)
		}
		e.ObjEnd()
	}
	e.ObjEnd()
}

func (m *TreeNode) Decode(d *jx.Decoder) error {
	seen := map[string]bool{}
	return d.Obj(func(d *jx.Decoder, key string) error {
		switch key {
		case "id":
			if seen["Id"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["Id"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := d.Str()
			if err != nil {
				return err
			}
			m.Id = v
			return nil
		case "parent":
			if seen["Parent"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["Parent"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			m.Parent = &TreeNode{}
			return m.Parent.Decode(d)
		case "children":
			if seen["Children"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["Children"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			return d.Arr(func(d *jx.Decoder) error {
				el := &TreeNode{}
				if err := el.Decode(d); err != nil {
					return err
				}
				m.Children = append(m.Children, el)
				return nil
			})
		case "named":
			if seen["Named"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["Named"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			if m.Named == nil {
				m.Named = make(map[string]*TreeNode)
			}
			return d.Obj(func(d *jx.Decoder, ks string) error {
				mk := ks
				var mv *TreeNode
				mv = &TreeNode{}
				if err := mv.Decode(d); err != nil {
					return err
				}
				m.Named[mk] = mv
				return nil
			})
		default:
			return fmt.Errorf("unknown field %q", key)
		}
	})
}

func (m *TreeNode) MarshalJSON() ([]byte, error) {
	var e jx.Encoder
	m.Encode(&e)
	return e.Bytes(), nil
}

func (m *TreeNode) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return m.Decode(d)
}

func (m *MutualA) Encode(e *jx.Encoder) {
	if m == nil {
		e.ObjStart()
		e.ObjEnd()
		return
	}
	e.ObjStart()
	if m.B != nil {
		e.FieldStart("b")
		m.B.Encode(e)
	}
	e.ObjEnd()
}

func (m *MutualA) Decode(d *jx.Decoder) error {
	seen := map[string]bool{}
	return d.Obj(func(d *jx.Decoder, key string) error {
		switch key {
		case "b":
			if seen["B"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["B"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			m.B = &MutualB{}
			return m.B.Decode(d)
		default:
			return fmt.Errorf("unknown field %q", key)
		}
	})
}

func (m *MutualA) MarshalJSON() ([]byte, error) {
	var e jx.Encoder
	m.Encode(&e)
	return e.Bytes(), nil
}

func (m *MutualA) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return m.Decode(d)
}

func (m *MutualB) Encode(e *jx.Encoder) {
	if m == nil {
		e.ObjStart()
		e.ObjEnd()
		return
	}
	e.ObjStart()
	if m.A != nil {
		e.FieldStart("a")
		m.A.Encode(e)
	}
	e.ObjEnd()
}

func (m *MutualB) Decode(d *jx.Decoder) error {
	seen := map[string]bool{}
	return d.Obj(func(d *jx.Decoder, key string) error {
		switch key {
		case "a":
			if seen["A"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["A"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			m.A = &MutualA{}
			return m.A.Decode(d)
		default:
			return fmt.Errorf("unknown field %q", key)
		}
	})
}

func (m *MutualB) MarshalJSON() ([]byte, error) {
	var e jx.Encoder
	m.Encode(&e)
	return e.Bytes(), nil
}

func (m *MutualB) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return m.Decode(d)
}

func (m *Reserved) Encode(e *jx.Encoder) {
	if m == nil {
		e.ObjStart()
		e.ObjEnd()
		return
	}
	e.ObjStart()
	if m.Active != "" {
		e.FieldStart("active")
		e.Str(m.Active)
	}
	e.ObjEnd()
}

func (m *Reserved) Decode(d *jx.Decoder) error {
	seen := map[string]bool{}
	return d.Obj(func(d *jx.Decoder, key string) error {
		switch key {
		case "active":
			if seen["Active"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["Active"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := d.Str()
			if err != nil {
				return err
			}
			m.Active = v
			return nil
		default:
			return fmt.Errorf("unknown field %q", key)
		}
	})
}

func (m *Reserved) MarshalJSON() ([]byte, error) {
	var e jx.Encoder
	m.Encode(&e)
	return e.Bytes(), nil
}

func (m *Reserved) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return m.Decode(d)
}

func (m *Everything) Encode(e *jx.Encoder) {
	if m == nil {
		e.ObjStart()
		e.ObjEnd()
		return
	}
	e.ObjStart()
	if m.Scalars != nil {
		e.FieldStart("scalars")
		m.Scalars.Encode(e)
	}
	if m.Optionals != nil {
		e.FieldStart("optionals")
		m.Optionals.Encode(e)
	}
	if m.Repeateds != nil {
		e.FieldStart("repeateds")
		m.Repeateds.Encode(e)
	}
	if m.EnumsAndMessages != nil {
		e.FieldStart("enumsAndMessages")
		m.EnumsAndMessages.Encode(e)
	}
	if m.MapKeys != nil {
		e.FieldStart("mapKeys")
		m.MapKeys.Encode(e)
	}
	if m.MapValues != nil {
		e.FieldStart("mapValues")
		m.MapValues.Encode(e)
	}
	if m.Oneof != nil {
		e.FieldStart("oneof")
		m.Oneof.Encode(e)
	}
	if m.WellKnown != nil {
		e.FieldStart("wellKnown")
		m.WellKnown.Encode(e)
	}
	if m.Tree != nil {
		e.FieldStart("tree")
		m.Tree.Encode(e)
	}
	if m.Reserved != nil {
		e.FieldStart("reserved")
		m.Reserved.Encode(e)
	}
	if len(m.Recursive) > 0 {
		e.FieldStart("recursive")
		e.ArrStart()
		for _, v := range m.Recursive {
			v.Encode(e)
		}
		e.ArrEnd()
	}
	switch v := m.Terminal.(type) {
	case *Everything_Done:
		e.FieldStart("done")
		e.Bool(v.Done)
	case *Everything_Error:
		e.FieldStart("error")
		e.Str(v.Error)
	}
	e.ObjEnd()
}

func (m *Everything) Decode(d *jx.Decoder) error {
	seen := map[string]bool{}
	return d.Obj(func(d *jx.Decoder, key string) error {
		switch key {
		case "scalars":
			if seen["Scalars"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["Scalars"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			m.Scalars = &ScalarTypes{}
			return m.Scalars.Decode(d)
		case "optionals":
			if seen["Optionals"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["Optionals"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			m.Optionals = &OptionalScalarTypes{}
			return m.Optionals.Decode(d)
		case "repeateds":
			if seen["Repeateds"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["Repeateds"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			m.Repeateds = &RepeatedScalarTypes{}
			return m.Repeateds.Decode(d)
		case "enumsAndMessages", "enums_and_messages":
			if seen["EnumsAndMessages"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["EnumsAndMessages"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			m.EnumsAndMessages = &EnumAndMessageFields{}
			return m.EnumsAndMessages.Decode(d)
		case "mapKeys", "map_keys":
			if seen["MapKeys"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["MapKeys"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			m.MapKeys = &MapKeyTypes{}
			return m.MapKeys.Decode(d)
		case "mapValues", "map_values":
			if seen["MapValues"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["MapValues"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			m.MapValues = &MapValueTypes{}
			return m.MapValues.Decode(d)
		case "oneof":
			if seen["Oneof"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["Oneof"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			m.Oneof = &OneofContainer{}
			return m.Oneof.Decode(d)
		case "wellKnown", "well_known":
			if seen["WellKnown"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["WellKnown"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			m.WellKnown = &WellKnownTypes{}
			return m.WellKnown.Decode(d)
		case "tree":
			if seen["Tree"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["Tree"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			m.Tree = &TreeNode{}
			return m.Tree.Decode(d)
		case "reserved":
			if seen["Reserved"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["Reserved"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			m.Reserved = &Reserved{}
			return m.Reserved.Decode(d)
		case "recursive":
			if seen["Recursive"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["Recursive"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			return d.Arr(func(d *jx.Decoder) error {
				el := &Everything{}
				if err := el.Decode(d); err != nil {
					return err
				}
				m.Recursive = append(m.Recursive, el)
				return nil
			})
		case "done":
			if seen["oneof:Terminal"] {
				return fmt.Errorf("multiple keys for oneof terminal")
			}
			seen["oneof:Terminal"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			val, err := d.Bool()
			if err != nil {
				return err
			}
			m.Terminal = &Everything_Done{Done: val}
			return nil
		case "error":
			if seen["oneof:Terminal"] {
				return fmt.Errorf("multiple keys for oneof terminal")
			}
			seen["oneof:Terminal"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			val, err := d.Str()
			if err != nil {
				return err
			}
			m.Terminal = &Everything_Error{Error: val}
			return nil
		default:
			return fmt.Errorf("unknown field %q", key)
		}
	})
}

func (m *Everything) MarshalJSON() ([]byte, error) {
	var e jx.Encoder
	m.Encode(&e)
	return e.Bytes(), nil
}

func (m *Everything) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return m.Decode(d)
}
