// Code generated by protoc-gen-go-jx. DO NOT EDIT.

package golden

import (
	fmt "fmt"
	jx "github.com/go-faster/jx"
)

func (m *ScalarTypes) Encode(e *jx.Encoder) {
	if m == nil {
		e.ObjStart()
		e.ObjEnd()
		return
	}
	e.ObjStart()
	e.ObjEnd()
}

func (m *ScalarTypes) Decode(d *jx.Decoder) error {
	return d.Obj(func(d *jx.Decoder, key string) error {
		switch key {
		default:
			return fmt.Errorf("unknown field %q", key)
		}
	})
}

func (m *ScalarTypes) MarshalJSON() ([]byte, error) {
	var e jx.Encoder
	m.Encode(&e)
	return e.Bytes(), nil
}

func (m *ScalarTypes) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return m.Decode(d)
}

func (m *OptionalScalarTypes) Encode(e *jx.Encoder) {
	if m == nil {
		e.ObjStart()
		e.ObjEnd()
		return
	}
	e.ObjStart()
	e.ObjEnd()
}

func (m *OptionalScalarTypes) Decode(d *jx.Decoder) error {
	return d.Obj(func(d *jx.Decoder, key string) error {
		switch key {
		default:
			return fmt.Errorf("unknown field %q", key)
		}
	})
}

func (m *OptionalScalarTypes) MarshalJSON() ([]byte, error) {
	var e jx.Encoder
	m.Encode(&e)
	return e.Bytes(), nil
}

func (m *OptionalScalarTypes) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return m.Decode(d)
}

func (m *RepeatedScalarTypes) Encode(e *jx.Encoder) {
	if m == nil {
		e.ObjStart()
		e.ObjEnd()
		return
	}
	e.ObjStart()
	e.ObjEnd()
}

func (m *RepeatedScalarTypes) Decode(d *jx.Decoder) error {
	return d.Obj(func(d *jx.Decoder, key string) error {
		switch key {
		default:
			return fmt.Errorf("unknown field %q", key)
		}
	})
}

func (m *RepeatedScalarTypes) MarshalJSON() ([]byte, error) {
	var e jx.Encoder
	m.Encode(&e)
	return e.Bytes(), nil
}

func (m *RepeatedScalarTypes) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return m.Decode(d)
}

func (m *Outer) Encode(e *jx.Encoder) {
	if m == nil {
		e.ObjStart()
		e.ObjEnd()
		return
	}
	e.ObjStart()
	e.ObjEnd()
}

func (m *Outer) Decode(d *jx.Decoder) error {
	return d.Obj(func(d *jx.Decoder, key string) error {
		switch key {
		default:
			return fmt.Errorf("unknown field %q", key)
		}
	})
}

func (m *Outer) MarshalJSON() ([]byte, error) {
	var e jx.Encoder
	m.Encode(&e)
	return e.Bytes(), nil
}

func (m *Outer) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return m.Decode(d)
}

func (m *Outer_Inner) Encode(e *jx.Encoder) {
	if m == nil {
		e.ObjStart()
		e.ObjEnd()
		return
	}
	e.ObjStart()
	e.ObjEnd()
}

func (m *Outer_Inner) Decode(d *jx.Decoder) error {
	return d.Obj(func(d *jx.Decoder, key string) error {
		switch key {
		default:
			return fmt.Errorf("unknown field %q", key)
		}
	})
}

func (m *Outer_Inner) MarshalJSON() ([]byte, error) {
	var e jx.Encoder
	m.Encode(&e)
	return e.Bytes(), nil
}

func (m *Outer_Inner) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return m.Decode(d)
}

func (m *Outer_Inner_DeepInner) Encode(e *jx.Encoder) {
	if m == nil {
		e.ObjStart()
		e.ObjEnd()
		return
	}
	e.ObjStart()
	e.ObjEnd()
}

func (m *Outer_Inner_DeepInner) Decode(d *jx.Decoder) error {
	return d.Obj(func(d *jx.Decoder, key string) error {
		switch key {
		default:
			return fmt.Errorf("unknown field %q", key)
		}
	})
}

func (m *Outer_Inner_DeepInner) MarshalJSON() ([]byte, error) {
	var e jx.Encoder
	m.Encode(&e)
	return e.Bytes(), nil
}

func (m *Outer_Inner_DeepInner) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return m.Decode(d)
}

func (m *EnumAndMessageFields) Encode(e *jx.Encoder) {
	if m == nil {
		e.ObjStart()
		e.ObjEnd()
		return
	}
	e.ObjStart()
	e.ObjEnd()
}

func (m *EnumAndMessageFields) Decode(d *jx.Decoder) error {
	return d.Obj(func(d *jx.Decoder, key string) error {
		switch key {
		default:
			return fmt.Errorf("unknown field %q", key)
		}
	})
}

func (m *EnumAndMessageFields) MarshalJSON() ([]byte, error) {
	var e jx.Encoder
	m.Encode(&e)
	return e.Bytes(), nil
}

func (m *EnumAndMessageFields) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return m.Decode(d)
}

func (m *MapKeyTypes) Encode(e *jx.Encoder) {
	if m == nil {
		e.ObjStart()
		e.ObjEnd()
		return
	}
	e.ObjStart()
	e.ObjEnd()
}

func (m *MapKeyTypes) Decode(d *jx.Decoder) error {
	return d.Obj(func(d *jx.Decoder, key string) error {
		switch key {
		default:
			return fmt.Errorf("unknown field %q", key)
		}
	})
}

func (m *MapKeyTypes) MarshalJSON() ([]byte, error) {
	var e jx.Encoder
	m.Encode(&e)
	return e.Bytes(), nil
}

func (m *MapKeyTypes) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return m.Decode(d)
}

func (m *MapValueTypes) Encode(e *jx.Encoder) {
	if m == nil {
		e.ObjStart()
		e.ObjEnd()
		return
	}
	e.ObjStart()
	e.ObjEnd()
}

func (m *MapValueTypes) Decode(d *jx.Decoder) error {
	return d.Obj(func(d *jx.Decoder, key string) error {
		switch key {
		default:
			return fmt.Errorf("unknown field %q", key)
		}
	})
}

func (m *MapValueTypes) MarshalJSON() ([]byte, error) {
	var e jx.Encoder
	m.Encode(&e)
	return e.Bytes(), nil
}

func (m *MapValueTypes) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return m.Decode(d)
}

func (m *OneofContainer) Encode(e *jx.Encoder) {
	if m == nil {
		e.ObjStart()
		e.ObjEnd()
		return
	}
	e.ObjStart()
	e.ObjEnd()
}

func (m *OneofContainer) Decode(d *jx.Decoder) error {
	return d.Obj(func(d *jx.Decoder, key string) error {
		switch key {
		default:
			return fmt.Errorf("unknown field %q", key)
		}
	})
}

func (m *OneofContainer) MarshalJSON() ([]byte, error) {
	var e jx.Encoder
	m.Encode(&e)
	return e.Bytes(), nil
}

func (m *OneofContainer) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return m.Decode(d)
}

func (m *WellKnownTypes) Encode(e *jx.Encoder) {
	if m == nil {
		e.ObjStart()
		e.ObjEnd()
		return
	}
	e.ObjStart()
	e.ObjEnd()
}

func (m *WellKnownTypes) Decode(d *jx.Decoder) error {
	return d.Obj(func(d *jx.Decoder, key string) error {
		switch key {
		default:
			return fmt.Errorf("unknown field %q", key)
		}
	})
}

func (m *WellKnownTypes) MarshalJSON() ([]byte, error) {
	var e jx.Encoder
	m.Encode(&e)
	return e.Bytes(), nil
}

func (m *WellKnownTypes) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return m.Decode(d)
}

func (m *TreeNode) Encode(e *jx.Encoder) {
	if m == nil {
		e.ObjStart()
		e.ObjEnd()
		return
	}
	e.ObjStart()
	e.ObjEnd()
}

func (m *TreeNode) Decode(d *jx.Decoder) error {
	return d.Obj(func(d *jx.Decoder, key string) error {
		switch key {
		default:
			return fmt.Errorf("unknown field %q", key)
		}
	})
}

func (m *TreeNode) MarshalJSON() ([]byte, error) {
	var e jx.Encoder
	m.Encode(&e)
	return e.Bytes(), nil
}

func (m *TreeNode) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return m.Decode(d)
}

func (m *MutualA) Encode(e *jx.Encoder) {
	if m == nil {
		e.ObjStart()
		e.ObjEnd()
		return
	}
	e.ObjStart()
	e.ObjEnd()
}

func (m *MutualA) Decode(d *jx.Decoder) error {
	return d.Obj(func(d *jx.Decoder, key string) error {
		switch key {
		default:
			return fmt.Errorf("unknown field %q", key)
		}
	})
}

func (m *MutualA) MarshalJSON() ([]byte, error) {
	var e jx.Encoder
	m.Encode(&e)
	return e.Bytes(), nil
}

func (m *MutualA) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return m.Decode(d)
}

func (m *MutualB) Encode(e *jx.Encoder) {
	if m == nil {
		e.ObjStart()
		e.ObjEnd()
		return
	}
	e.ObjStart()
	e.ObjEnd()
}

func (m *MutualB) Decode(d *jx.Decoder) error {
	return d.Obj(func(d *jx.Decoder, key string) error {
		switch key {
		default:
			return fmt.Errorf("unknown field %q", key)
		}
	})
}

func (m *MutualB) MarshalJSON() ([]byte, error) {
	var e jx.Encoder
	m.Encode(&e)
	return e.Bytes(), nil
}

func (m *MutualB) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return m.Decode(d)
}

func (m *Reserved) Encode(e *jx.Encoder) {
	if m == nil {
		e.ObjStart()
		e.ObjEnd()
		return
	}
	e.ObjStart()
	e.ObjEnd()
}

func (m *Reserved) Decode(d *jx.Decoder) error {
	return d.Obj(func(d *jx.Decoder, key string) error {
		switch key {
		default:
			return fmt.Errorf("unknown field %q", key)
		}
	})
}

func (m *Reserved) MarshalJSON() ([]byte, error) {
	var e jx.Encoder
	m.Encode(&e)
	return e.Bytes(), nil
}

func (m *Reserved) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return m.Decode(d)
}

func (m *Everything) Encode(e *jx.Encoder) {
	if m == nil {
		e.ObjStart()
		e.ObjEnd()
		return
	}
	e.ObjStart()
	e.ObjEnd()
}

func (m *Everything) Decode(d *jx.Decoder) error {
	return d.Obj(func(d *jx.Decoder, key string) error {
		switch key {
		default:
			return fmt.Errorf("unknown field %q", key)
		}
	})
}

func (m *Everything) MarshalJSON() ([]byte, error) {
	var e jx.Encoder
	m.Encode(&e)
	return e.Bytes(), nil
}

func (m *Everything) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return m.Decode(d)
}
